openapi: 3.0.1
info:
  title: BON in a Box - Script service
  contact:
    email: jean-michel.lord@mcgill.ca
  version: 1.0.0
servers:
- url: http://0.0.0.0:5000
  description: script service URL
tags:
- name: placeholder
  description: We could use tags
paths:
  /script/{scriptPath}:
    get:
      tags: []
      summary: Run this script
      description: Run this script ... decription ...
      operationId: runScript
      parameters:
      - name: scriptPath
        in: path
        description: Where to find the script in ./script folder
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "400":
          description: Bad request
        "404":
          description: Script not found
      x-swagger-router-controller: Default
components:
  schemas:
    inline_response_200:
      type: object
      properties:
        message:
          type: string
          example: Script completed!
        file:
          type: string
          example: map.tiff
      example:
        file: map.tiff
        message: Script completed!
      xml:
        name: Result
