## Load required packages - libraries to run the script ####

### Check and install necessary libraries - packages  ####
packagesPrev<- installed.packages()[,"Package"] # Check and get a list of installed packages in this machine and R version
packagesNeed<- c("magrittr", "dplyr" , "this.path", "rjson", "sf", "raster", "pbapply", "ggplot2", "Polychrome", "ggpubr", "purrr"); packagesNeed<- packagesNeed[!packagesNeed==""] # Define the list of required packages to run the script
new.packages <- packagesNeed[!(packagesNeed %in% packagesPrev)]; if(length(new.packages)) {install.packages(new.packages, binary=T, force=T, dependencies = T, repos= "https://packagemanager.posit.co/cran/__linux__/jammy/latest")} # Check and install required packages that are not previously installed
packagesRemotes<- c(""); packagesRemotes<- packagesRemotes[!packagesRemotes==""] # Define the list of required packages to run that are avaliable from other sources
new.packagesRemotes <- packagesRemotes[!(packagesRemotes %in% packagesPrev)]; if(length(packagesRemotes)) {lapply(packagesRemotes, function(x) devtools::install_github(x))} # Check and install required packages that are not previously installed

### Load the necessary libraries into the script environment ####
packagesList<-list("magrittr", "terra", "raster", "ggplot2") # Explicitly list the required packages throughout the entire routine. Explicitly listing the required packages throughout the routine ensures that only the necessary packages are listed. Unlike 'packagesNeed', this list includes packages with functions that cannot be directly called using the '::' syntax. By using '::', specific functions or objects from a package can be accessed directly without loading the entire package. Loading an entire package involves loading all the functions and objects 
lapply(packagesList, library, character.only = TRUE)  # Load libraries - packages  

## Set enviroment variables ####

#### Define output folder path ####
##### Option 1: Setting for production pipeline purposes. ####
###### This is designed for use in a production environment or workflow.
Sys.setenv(outputFolder = "/path/to/output/folder")

##### Option 2: Recommended for debugging purposes to be used as a testing environment. ####
###### This is designed to facilitate script testing and correction
if ( (!exists("outputFolder"))  ) {
  outputFolder<- {x<- this.path::this.path();  file_prev<-  paste0(gsub("/scripts.*", "/output", x), gsub("^.*/scripts", "", x)  ); options<- tools::file_path_sans_ext(file_prev) %>% {c(., paste0(., ".R"), paste0(., "_R"))}; folder_out<- options %>% {.[file.exists(.)]} %>% {.[which.max(sapply(., function(info) file.info(info)$mtime))]}; folder_final<- list.files(folder_out, full.names = T) %>% {.[which.max(sapply(., function(info) file.info(info)$mtime))]} }
}

#### Define input folder path ####
##### Set the 'input' environment variables. The 'input' environment contains the specified inputs from the ByB platform.
##### The input file 'input.json' is generated by executing the 'Run Script' command in the ByB platform.
input <- rjson::fromJSON(file=file.path(outputFolder, "input.json")) # Load input file

##### Adjusts the input values paths ####
###### This section adjusts the input values based on specific conditions to rectify and prevent errors in the input paths
input<- lapply(input, function(x) { if (!is.null(x) && length(x) > 0 && grepl("/", x) && !grepl("http://", x)  ) { 
  sub("/output/.*", "/output", outputFolder) %>% dirname() %>%  file.path(x) %>% {gsub("//+", "/", .)}  } else{x} }) 

##  Script body ####

### Load grid ####
base_raster<- raster::raster(input$grid_map)

### Load Spatial Records ####
spatial_records<- sf::st_read(input$occ_points) %>% sf::st_transform(sf::st_crs(base_raster)$proj4string)
raster_points <- raster::rasterize(spatial_records, base_raster, field = 1) ### Rasterize records ####

### Estimate Spatial Distance Density Map ####
distance_points <- terra::distance(raster_points); 
distance_map<- terra::mask(distance_points, base_raster)

### Estimate tresholds ####
list_thresholds<- c(quantile(distance_map, seq(0.1, 1, 0.1)), input$DispersalDistance_m) %>% sort()
data_hypothesis<- data.frame(hypothesis= seq_along(list_thresholds), distance_m= round(list_thresholds))

### Estimate discrete populations hypotesis ####
  list_hypothesis<- pbapply::pblapply(seq_along(list_thresholds), function(i){
  
  threshold <- list_thresholds[i]  #
  distance_threshold<- distance_points; distance_threshold[distance_threshold<=threshold]<- 1; distance_threshold[distance_threshold>threshold]<- 0; 
  distance_mask<- terra::mask(distance_threshold, base_raster) %>% terra::extend(extent(distance_threshold)*2);  distance_mask[is.na(distance_mask)]<- 0
  
  contours<- rasterToContour(distance_mask)
  contours_pols<- sf::st_as_sf(contours) %>%  sf::st_polygonize() %>%  sf::st_buffer(0) %>% 
    terra::vect() %>% terra::aggregate() %>% sf::st_as_sf() %>% sf::st_cast("POLYGON")
  
  distance_matrix <- sf::st_distance(contours_pols)
  dist_object <- as.dist(distance_matrix)
  clustering <- hclust(dist_object, method = "complete")
  contours_pols$pop <- cutree(clustering, h = threshold)
  contours_pols$pop_name <- paste0("pop",  contours_pols$pop)
  final_hypothesis<- cbind(data_hypothesis[i,], contours_pols) %>% sf::st_as_sf()
  final_hypothesis$pop_name<- factor(final_hypothesis$pop_name, levels = unique(final_hypothesis$pop_name))
  
  list(final_hypothesis_sf= final_hypothesis, 
       final_hypothesis_tif= raster::rasterize(final_hypothesis, base_raster, field = "pop") %>% terra::rast() %>% setNames(unique(paste0("hip", final_hypothesis$hypothesis,"_dist", round(final_hypothesis$distance)))) )

  })
  
#### Organize spatial information 
list_hypothesis_sf<- purrr::map(list_hypothesis, "final_hypothesis_sf")
list_hypothesis_tif<- purrr::map(list_hypothesis, "final_hypothesis_tif") %>% terra::rast() 

#### Summary table with the distance and number of distinct populations per hypothesis ###
table_hypothesis<- plyr::rbind.fill(list_hypothesis_sf) %>% 
  sf::st_drop_geometry() %>% dplyr::group_by(hypothesis, distance_m) %>% 
  dplyr::summarise(npop= dplyr::n_distinct(pop))

### Apply Color Mapping to Hypothesis Rasters ####
list_hypothesis_tifcol<- list_hypothesis_tif
discrete_vals<- max(table_hypothesis$npop)
cols_vals<- Polychrome::createPalette(discrete_vals,  c("#ff0000", "#00ff00", "#0000ff")) %>% setNames(paste0("pop", seq(discrete_vals)))
for(i in seq(terra::nlyr(list_hypothesis_tifcol)) ){ print(i)
levels(list_hypothesis_tifcol[[i]]) <- data.frame(values= seq(discrete_vals), label= paste0("pop", seq(discrete_vals)))
coltab(list_hypothesis_tifcol[[i]]) <- data.frame(values= seq(discrete_vals), cols= cols_vals )
}
list_hypothesis_tifcol<- list_hypothesis_tifcol %>% setNames(names(list_hypothesis_tif))

### Plot discrete populations hypotesis ####
plot_results<- pbapply::pblapply(list_hypothesis_sf, function(x)
    { ggplot()+geom_sf(data= x, aes(fill= pop_name))+theme_void()+
    scale_fill_manual(values =  cols_vals) +
    ggtitle(unique(paste0("hip", x$hypothesis,"_", round(x$distance), "m")))+
      theme(base_size = 8, legend.position = "none",
            plot.title = element_text(size = 8))
  }) %>% {ggpubr::ggarrange(plotlist = .)}
  

##  Export results ####

### Export distance map
distance_map_path <- file.path(outputFolder,paste0("distance_map", ".tif"))
terra::writeRaster(distance_map, distance_map_path, overwrite = TRUE ) # write result

### Export summary tab
data_hypothesis_path <- file.path(outputFolder, paste0("data_hypothesis", ".csv")) # Define the file path for the 'val_wkt_path' output
write.csv(table_hypothesis, data_hypothesis_path, row.names = F) # write result

### Export summary plot
plot_hypothesis_path <- file.path(outputFolder, paste0("plot_hypothesis", ".jpg")) # Define the file path for the 'val_wkt_path' output
ggsave(plot_hypothesis_path, plot_results )
  
### Export vector results
folder_hypothesis_vector<- file.path(outputFolder, "folder_hypothesis_vector"); dir.create(folder_hypothesis_vector)
lapply(list_hypothesis_sf, function(x) {
  sf::st_write(x, 
               file.path(folder_hypothesis_vector, unique(paste0("hip", x$hypothesis,"_dist", round(x$distance), ".GeoJSON"))), delete_dsn= T, driver = "GeoJSON")
})

### Export raster results
folder_hypothesis_tif<- file.path(outputFolder, "hypothesis_tif_path"); dir.create(folder_hypothesis_tif)
layer_paths<-c()

for (i in seq(terra::nlyr(list_hypothesis_tifcol))) {
  layer_path <- file.path(folder_hypothesis_tif, names(list_hypothesis_tifcol)[[i]] ) %>% paste0(".tif")
  terra::writeRaster(list_hypothesis_tifcol[[i]], layer_path, gdal=c("COMPRESS=DEFLATE", "TFW=YES"), filetype = "GTiff", overwrite = TRUE ) # write result
  fp <- paste0(layer_path[1])
  layer_paths <- cbind(layer_paths,fp)
}


## Set Output list ####
output<- list(
  distance_map= distance_map_path,
  data_hypothesis = data_hypothesis_path, 
              plot_hypothesis = plot_hypothesis_path,
              map_hypothesis= layer_paths,
  folder_raster_hypothesis= folder_hypothesis_tif,
  folder_polygon_hypothesis= folder_hypothesis_vector
  )


## Outputing result to JSON ####
setwd(outputFolder)
jsonData <- rjson::toJSON(output, indent=2)
write(jsonData, file.path(outputFolder,"output.json"))