# Load required packages - libraries to run the script ####

## Check and install necessary libraries - packages  ####
packagesPrev<- installed.packages()[,"Package"] # Check and get a list of installed packages in this machine and R version
packagesNeed<- c("magrittr", "devtools", "this.path", "terra", "raster", "sf", "fasterize", "this.path", "rjson");  packagesNeed<- packagesNeed[!packagesNeed==""]  # Define the list of required packages to run the script
new.packages <- packagesNeed[!(packagesNeed %in% packagesPrev)]; if(length(new.packages)) {install.packages(new.packages, binary=T, force=T, dependencies = F, repos= "https://packagemanager.posit.co/cran/__linux__/jammy/latest")} # Check and install required packages that are not previously installed

packagesRemotes<- c(""); packagesRemotes<- packagesRemotes[!packagesRemotes==""]  # Define the list of required packages to run that are avaliable from other sources
new.packagesRemotes <- packagesRemotes[!(packagesRemotes %in% packagesPrev)]; if(length(packagesRemotes)) {lapply(packagesRemotes, function(x) devtools::install_github(x))} # Check and install required packages that are not previously installed

## Load the necessary libraries into the script environment ####
packagesList<-list("magrittr", "terra") # Explicitly list the required packages throughout the entire routine. Explicitly listing the required packages throughout the routine ensures that only the necessary packages are listed. Unlike 'packagesNeed', this list includes packages with functions that cannot be directly called using the '::' syntax. By using '::', specific functions or objects from a package can be accessed directly without loading the entire package. Loading an entire package involves loading all the functions and objects 
lapply(packagesList, library, character.only = TRUE)  # Load libraries - packages  


# Set enviroment variables ####

### Define output folder path ####
#### Option 1: Setting for production pipeline purposes. ####
##### This is designed for use in a production environment or workflow.
Sys.setenv(outputFolder = "/path/to/output/folder")

#### Option 2: Recommended for debugging purposes to be used as a testing environment. ####
##### This is designed to facilitate script testing and correction
if ( (!exists("outputFolder"))  ) {
  outputFolder<- {x<- this.path::this.path();  file_prev<-  paste0(gsub("/scripts.*", "/output", x), gsub("^.*/scripts", "", x)  ); options<- tools::file_path_sans_ext(file_prev) %>% {c(., paste0(., ".R"), paste0(., "_R"))}; folder_out<- options %>% {.[file.exists(.)]} %>% {.[which.max(sapply(., function(info) file.info(info)$mtime))]}; folder_final<- list.files(folder_out, full.names = T) %>% {.[which.max(sapply(., function(info) file.info(info)$mtime))]} }
}

### Define input folder path ####
#### Set the 'input' environment variables. The 'input' environment contains the specified inputs from the ByB platform.
#### The input file 'input.json' is generated by executing the 'Run Script' command in the ByB platform.
input <- rjson::fromJSON(file=file.path(outputFolder, "input.json")) # Load input file

#### Adjusts the input values paths ####
##### This section adjusts the input values based on specific conditions to rectify and prevent errors in the input paths
input<- lapply(input, function(x) { if (!is.null(x) && length(x) > 0 && grepl("/", x) && !grepl("http://", x)  ) { 
  sub("/output/.*", "/output", outputFolder) %>% dirname() %>%  file.path(x) %>% {gsub("//+", "/", .)}  } else{x} }) 

#  Script body ####

  # Load and convert the study area to aggregate polygon limits and project it to the defined EPSG coordinate system
  crs_basemap<- raster::crs( paste0("+init=epsg:", input$EPSG) )
  
  vector_polygon<-  terra::vect(input$StudyArea_polygon) %>% terra::aggregate()  %>%  terra::project( crs_basemap    )
  
  # Convert the vector polygon to the GeoJSON format and transform its coordinate reference system to 4326 (WGS84) to make it compatible with the Leaflet interactive JavaScript library
  sf_polygon<- sf::st_as_sf(vector_polygon) 
  sf_polygon_4326<- sf_polygon %>% sf::st_transform(4326)
  
  # Create bbox reference
  bbox_base<- sf_polygon  %>% sf::st_bbox() 
  extent_base <- bbox_base %>% raster::extent()
  
  
  # create base grid
  raster_base <- raster::raster(extent_base,crs = crs_basemap, res= input$gridRes_meters )
  raster_study_area<- fasterize::fasterize(sf_polygon, raster_base) %>% terra::rast()
  
  levels(raster_study_area)<- data.frame(values= 1, label= "Study area")
  coltab(raster_study_area)<- data.frame(values= 1, cols= "gray")
  
  #  Export results ####
  raster_study_area_path<- file.path(outputFolder, "raster_study_area_path.tif") # Define the file path for the 'val_wkt_path' output
  terra::writeRaster(raster_study_area, raster_study_area_path, gdal=c("COMPRESS=DEFLATE", "TFW=YES"), filetype = "GTiff", overwrite = TRUE )
  
  json_study_area_path<- file.path(outputFolder, "json_study_area_path.GeoJSON") # Define the file path for the 'val_wkt_path' output
  sf::st_write(sf_polygon_4326, json_study_area_path, delete_dsn= T, driver = "GeoJSON")
  
  
   
  # Set Output list ####
  output<- list(StudyArea_polygon= json_study_area_path, StudyArea_grid= raster_study_area_path)
  
  # Outputing result to JSON ####
  setwd(outputFolder)
  jsonlite::write_json(output, "output.json", auto_unbox = TRUE, pretty = TRUE)
  