#### Load required packages - libraries to run the script ####

# Install necessary libraries - packages  
packagesPrev<- installed.packages()[,"Package"] # Check and get a list of installed packages in this machine and R version
packagesNeed<- c("magrittr", "terra", "raster", "sf", "pbapply", "this.path", "rjson", "tools", "auk") # Define the list of required packages to run the script
new.packages <- packagesNeed[!(packagesNeed %in% packagesPrev)]; if(length(new.packages)) {install.packages(new.packages, binary=T, force=T, dependencies = F, repos= "https://packagemanager.posit.co/cran/__linux__/jammy/latest")} # Check and install required packages that are not previously installed

# Load libraries
packagesList<-list("magrittr", "terra") # Explicitly list the required packages throughout the entire routine. Explicitly listing the required packages throughout the routine ensures that only the necessary packages are listed. Unlike 'packagesNeed', this list includes packages with functions that cannot be directly called using the '::' syntax. By using '::', specific functions or objects from a package can be accessed directly without loading the entire package. Loading an entire package involves loading all the functions and objects 
lapply(packagesList, library, character.only = TRUE)  # Load libraries - packages  


#### Set enviroment variables ####

# Set the 'outputFolder' environment variables
# The environment variable refers to the path of the output folder for the entire routine
# 'outputFolder' allows interaction with the output folder of the routine and access to nearby paths, such as the input folder ('input')

# There are two options to set 'outputFolder'
# Please select only one of the two options, while silencing the other with the '#' syntaxis: 

# Option 1: Setting for production pipeline purposes. This is designed for use in a production environment or workflow.
Sys.setenv(outputFolder = "/path/to/output/folder")

# Option 2: Recommended for debugging purposes to be used as a testing environment. This is designed to facilitate script testing and correction
if ( (!exists("outputFolder"))  ) {
  outputFolder<- {x<- this.path::this.path();  file_prev<-  paste0(gsub("/scripts.*", "/output", x), gsub("^.*/scripts", "", x)  ); options<- tools::file_path_sans_ext(file_prev) %>% {c(., paste0(., ".R"), paste0(., "_R"))}; folder_out<- options %>% {.[file.exists(.)]} %>% {.[which.max(sapply(., function(info) file.info(info)$mtime))]}; folder_final<- list.files(folder_out, full.names = T) %>% {.[which.max(sapply(., function(info) file.info(info)$mtime))]} }
}

# Set the 'input' environment variables. The 'input' environment contains the specified inputs from the ByB platform.
# The input file 'input.json' is generated by executing the 'Run Script' command in the ByB platform.
input <- rjson::fromJSON(file=file.path(outputFolder, "input.json")) # Load input file

# This section adjusts the input values based on specific conditions to rectify and prevent errors in the input paths
input<- lapply(input, function(y) lapply(y, function(x)  {if (!is.null(x) && length(x) > 0 && grepl("/", x) && !grepl("http:", x)  ) { 
  sub("/output/.*", "/output", outputFolder) %>% dirname() %>%  file.path(x) %>% {gsub("//+", "/", .)}  } else if(!is.null(x) && length(x) > 0 && x %in% c("NULL", "NA")){NULL} else {x} }) %>% unlist()) 





#### Set enviroment variables ####

# Set the 'outputFolder' environment variables
# The environment variable refers to the path of the output folder for the entire routine
# 'outputFolder' allows interaction with the output folder of the routine and access to nearby paths, such as the input folder ('input')

# There are two options to set 'outputFolder'
# Please select only one of the two options, while silencing the other with the '#' syntaxis: 

# Precargar datos de ocurrencia y listas
ebird_habitat<- read.csv(input$auk_covars_file)


####  Script body ####
#time to decimal function
time_to_decimal <- function(x) {x <- lubridate::hms(x, quiet = TRUE); lubridate::hour(x) + lubridate::minute(x) / 60 + lubridate::second(x) / 3600} # function para convertir fechas en decimales

# Clean ebd_zf -data standaritation
ebd_occ <- ebird_habitat  %>% dplyr::rowwise() %>%
  dplyr::mutate(observation_count = if(observation_count %in% "X"){NA}else{observation_count}) %>%  # Convertir en observation_count X observaciones en NA
  dplyr::mutate(observation_count = as.integer(observation_count), # convertir observation_count en integer
                # effort_distance_km to 0 for non-travelling counts
                effort_distance_km = dplyr::if_else(protocol_type != "Traveling", 0, effort_distance_km), # establecer esfuerzo de muestreo effor_distance_km en 0 cuando protocol sea igual a Traveling
                #time_observations_started = time_to_decimal(time_observations_started),  # convertir fechas en decimales
                year = lubridate::year(observation_date),# crrear columna año
                day_of_year = lubridate::yday(observation_date),
                species_observed = ifelse(isTRUE(species_observed),1,0) ) # crear columna dias



# filter prior to creating occupancy model data
ebird_filtered <- dplyr::filter(ebd_occ, 
                                number_observers <= input$max_obs,
                                number_observers >= input$min_obs
                                )


# Data formatting
occ <- auk::filter_repeat_visits(ebird_filtered, 
                            min_obs = input$min_obs, max_obs = input$max_obs,
                            annual_closure = input$annual_closure,
                            n_days = input$n_days,
                            date_var = "observation_date",
                            site_vars = input$site_vars)



# format for unmarked

site_covs_input<- lapply(input$site_covs, function(y) { text_ext<- tools::file_ext(y)
if(text_ext != ""){
  if(file.exists(y)){y}else{NULL}
} else {
  test_folder<- dir.exists(y)
  if(test_folder){ list.files(y, full.names = T, recursive = F, pattern = "\\.tif") %>%  {.[!grepl("\\.tfw$|~$", .)]} } else { y }
}
})  %>% unlist()  %>%  basename() %>% tools::file_path_sans_ext()


site_covs<- site_covs_input %>% {.[. %in% names(ebird_habitat)]}



obs_covs<- input$obs_covs %>% strsplit( ",\\s*") %>% unlist() %>% trimws()



occ_wide <- auk::format_unmarked_occu(occ, 
                                 site_id = "site", 
                                 response = "species_observed",
                                 site_covs = site_covs,
                                 obs_covs = obs_covs)


occ_wide_path<- file.path(outputFolder, "occ_wide.csv") # Define the file path for the 'val_wkt_path' output
write.csv(occ_wide, occ_wide_path, row.names = F ) # Write the 'val_wkt_path' output


#### Outputing result to JSON ####
output<- list(occ_wide_unmark= occ_wide_path)

# Write the output list to the 'output.json' file in JSON format
setwd(outputFolder)
jsonlite::write_json(output, "output.json", auto_unbox = TRUE, pretty = TRUE)
