/**
* BON in a Box - Script service
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* Contact: jean-michel.lord@mcgill.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.server.models


/**
 * 
 * @param text 
 * @param doi 
 */
data class InfoReferences(
    val text: kotlin.String? = null,
    val doi: kotlin.String? = null
) 

