/**
* BON in a Box - Script service
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* Contact: jean-michel.lord@mcgill.ca
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.server.models

import org.openapitools.server.models.InfoInputs
import org.openapitools.server.models.InfoOutputs
import org.openapitools.server.models.InfoReferences

/**
 * 
 * @param script 
 * @param description 
 * @param externalLink 
 * @param inputs 
 * @param outputs 
 * @param references 
 */
data class Info(
    val script: kotlin.String? = null,
    val description: kotlin.String? = null,
    val externalLink: kotlin.String? = null,
    val inputs: kotlin.collections.Map<kotlin.String, InfoInputs>? = null,
    val outputs: kotlin.collections.Map<kotlin.String, InfoOutputs>? = null,
    val references: kotlin.collections.List<InfoReferences>? = null
) 

