## Base compose file. Automatically merged with compose.override.yml when running
##   docker compose up
version: "3.7"

services:
# This can be accessed within the docker network with http://biab-script-server:8081/script/...
  script-server:
    container_name: biab-script-server
    volumes:
      - ./scripts:/scripts:ro
      - ./pipelines:/pipelines:ro
      - ./output:/output:rw
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - '8080'
    environment:
      - SCRIPT_LOCATION=/scripts
      - PIPELINES_LOCATION=/pipelines
      - OUTPUT_LOCATION=/output
      - JUPYTERHUB_API_TOKEN=${JUPYTERHUB_API_TOKEN}
      - GBIF_USER=${GBIF_USER}
      - GBIF_PWD=${GBIF_PWD}
      - GBIF_EMAIL=${GBIF_EMAIL}
      - HOST_PATH=${PWD}

  http-gateway:
    container_name: http-rev-prox
    image: nginx
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./output:/static/output:ro
    depends_on:
      - script-server
