## Start this configuration with command
##   docker compose -f compose.yml -f compose.dev.yml up
version: "3.7"

services:
## UI server to use when developing UI code
  ui:
    container_name: biab-ui
    image: node:16.13.1-alpine3.13
    user: "node"
    volumes:
      - './ui:/app:rw'
    working_dir: "/app"
    command: sh -c "cd BonInABoxScriptService; npm run build; cd -; npm start;"
    expose:
      - '3000'
    environment:
      - CHOKIDAR_USEPOLLING=true 
    depends_on:
      - script-server

  http-gateway:
    volumes:
      - ./http-proxy/conf.d:/etc/nginx/conf.d:rw
    depends_on:
      - ui

## In the DEV version, using a volume and a single docker. To rebuild without restarting everything, use
## docker exec -it biab-script-server sh -c "cd /home/gradle/project/ && gradle build"
  script-server:
    build:
      context: ./script-server
      dockerfile: Dockerfile.dev
    volumes:
      - ./script-server:/home/gradle/project:rw
    working_dir: /home/gradle/project
    environment:
      - R_LIBS_USER=/home/gradle/project/r-libs-dev
    command: gradle run

## Server to use when making changes to the OpenAPI specification
  # openapi_swagger:
  #   container_name: swagger_editor
  #   image: swaggerapi/swagger-editor
  #   # Swagger editor will be available at port :80 or https://localhost
  #   ports:
  #     - "8082:8080"
  #   # Swagger File to feed the Swagger Editor
  #   # Base URL to point for consulting the Swagger https://localhost/swagger
  #   environment:
  #     SWAGGER_FILE: openapi.yaml
  #     BASE_URL: /swagger
  #   volumes:
  #     - ./script-server/api/:/app
