## This file is automatically added to compose.yml when running
##   docker compose up
version: "3.7"

services:

## UI server to use when you just want to use the UI
  ui-prod:
    container_name: biab-ui-prod
    image: geobon/bon-in-a-box:ui
    # build:
    #   context: ./ui
    #   dockerfile: Dockerfile.prod
    expose:
      - '80'
    depends_on:
      - script-server

  http-gateway:
    volumes:
    - ./http-proxy/conf.d-prod:/etc/nginx/conf.d:ro
    depends_on:
      - ui-prod

  script-server:
    image: geobon/bon-in-a-box:script-server
    # build:
    #    context: ./script-server/
    #    dockerfile: Dockerfile.prod