# This file specifies the environment that will be used to run each script language.
# It can use the default GEO BON images, or compile it's own images.

services:
  runner-conda:
    image: geobon/bon-in-a-box:runner-conda
    # build:
    #  context: ${PIPELINE_REPO_PATH}/runners
    #  dockerfile: conda-dockerfile
    tty: true # Needed to keep the container alive, waiting for requests.

  runner-julia:
    image: geobon/bon-in-a-box:runner-julia
    # build:
    #   context: ${PIPELINE_REPO_PATH}/runners
    #   dockerfile: julia-dockerfile
    command: sh # Avoids launching julia session that will not be used.
    tty: true # Needed to keep the container alive, waiting for requests.
