# This file specifies the environment that will be used to run each script language.
# It can use the default GEO BON images, or compile it's own images.

services:
  runner-conda:
    image: ghcr.io/geo-bon/bon-in-a-box-pipelines/runner-conda
    # build:
    #   context: ${PIPELINE_REPO_PATH}/runners/conda
    #   dockerfile: conda-dockerfile
    tty: true # Needed to keep the container alive, waiting for requests.

  runner-julia:
    image: ghcr.io/geo-bon/bon-in-a-box-pipelines/runner-julia
    # build:
    #   context: ${PIPELINE_REPO_PATH}/runners/julia
    #   dockerfile: julia-dockerfile
    command: sh # Avoids launching julia session that will not be used.
    tty: true # Needed to keep the container alive, waiting for requests.
