version: "3.7"

services:
# This can be accessed on localhost:8081/script/..., or within the docker network with script-server1:8081/script/...
  script-server:
    build:
      context: ./script-server/docker
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./script-server/:/home/node/app:rw
      - ./scripts:/scripts:r
      - ./output:/output:rw
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - SCRIPT_LOCATION=/scripts
      - OUTPUT_LOCATION=/output
      - NODE_ENV=development
      - R_LIBS_USER=/home/node/app/r-libs
    command: "npm start"

  # ui:
  #   container_name: biab-ui
  #   build:
  #     context: ./ui
  #     dockerfile: Dockerfile
  #   volumes:
  #     - './ui:/app'
  #     - '/app/node_modules'
  #   ports:
  #     - 3001:3000
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true 
  #   depends_on:
  #     - script-server

  # openapi_swagger:
  #   container_name: swagger_editor
  #   image: swaggerapi/swagger-editor
  #   # Swagger editor will be available at port :80 or https://localhost
  #   ports:
  #     - "80:8080"
  #   # Swagger File to feed the Swagger Editor
  #   # Base URL to point for consulting the Swagger https://localhost/swagger
  #   environment:
  #     SWAGGER_FILE: schema.json
  #     BASE_URL: /swagger
  #   volumes:
  #     - ./api/:/app
  #   depends_on:
  #     - script-server1
  #     - script-server2
