version: "3.7"

# This file specifies the environment that will be used to run each script language.
# It can use the default GEO BON images, or compile it's own images.

services:
  runner-r:
    image: geobon/bon-in-a-box:runner-r
    # build:
    #   context: ./runners
    #   dockerfile: r-dockerfile
    command: sh # Override default command to avoid launching R-studio server.
    tty: true # Needed to keep the container alive, waiting for requests.

  runner-julia:
    image: geobon/bon-in-a-box:runner-julia
    # build:
    #   context: ./runners
    #   dockerfile: julia-dockerfile
    command: sh # Avoids launching julia session that will not be used.
    tty: true # Needed to keep the container alive, waiting for requests.

  tiler:
    platform: linux/x86_64
