## Start this configuration with command
##   docker compose -f compose.yml -f compose.dev.yml up
version: "3.7"

services:
## UI server to use when developing UI code
  ui:
    container_name: biab-ui
    build:
      context: ./ui
      dockerfile: Dockerfile.dev
    user: "node"
    volumes:
      - './ui:/app:rw'
    working_dir: "/app"
    command: sh -c "cd BonInABoxScriptService; npm run build; cd -; npm install; npm start;"
    expose:
      - '3000'
    environment:
      - CHOKIDAR_USEPOLLING=true 
      # https://github.com/facebook/create-react-app/issues/11779
      - WDS_SOCKET_PORT=0
    depends_on:
      - script-server
      - tiler

  http-gateway:
    volumes:
      - ./http-proxy/conf.d:/etc/nginx/conf.d:rw
    depends_on:
      - ui
      - openapi_swagger

## In the DEV version, using a volume and a single docker. To rebuild without restarting everything, use
## docker exec -it biab-script-server sh -c "cd /home/gradle/project/ && gradle build"
  script-server:
    build:
      context: ./script-server
      dockerfile: Dockerfile.dev
    volumes:
      - ./script-server:/home/gradle/project:rw
    working_dir: /home/gradle/project
    command: gradle run
    environment:
      DEV: true

## Server to use when making changes to the OpenAPI specification.
  openapi_swagger:
    container_name: swagger_editor
    image: swaggerapi/swagger-editor
    expose:
      - "8080"
    environment:
      SWAGGER_FILE: openapi.yaml
      BASE_URL: /swagger
    volumes:
      - ./script-server/api/:/app
