## Base compose file. Automatically merged with compose.override.yml when running
##   docker compose up
version: "3.7"

services:
# This can be accessed on localhost:8081/script/..., or within the docker network with script-server1:8081/script/...
  script-server:
    container_name: biab-script-server
    build:
      context: ./script-server/docker
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./script-server/:/home/node/app:rw
      - ./scripts:/scripts:ro
      - ./output:/output:rw
    expose:
      - '8081'
    environment:
      - PORT=8081
      - SCRIPT_LOCATION=/scripts
      - OUTPUT_LOCATION=/output
      - NODE_ENV=development
      - R_LIBS_USER=/home/node/app/r-libs
    command: "npm start"

  kotlin-server:
    container_name: biab-script-server-kotlin
    volumes:
      - ./scripts:/scripts:ro
      - ./output:/output:rw
    ports:
      - '8083:8080'
    environment:
      - SCRIPT_LOCATION=/scripts
      - OUTPUT_LOCATION=/output

  http-gateway:
    container_name: http-rev-prox
    image: nginx
    ports:
      - '80:80'
    #- '443:443' configure https one day...
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./output:/static/output:ro
    depends_on:
      - script-server
