## Base compose file. Automatically merged with compose.override.yml when running
##   docker compose up
version: "3.7"

services:
# This can be accessed within the docker network with http://biab-script-server:8081/script/...
  script-server:
    container_name: biab-script-server
    volumes:
      - ./scripts:/scripts:ro
      - ./output:/output:rw
    expose:
      - '8080'
    environment:
      - SCRIPT_LOCATION=/scripts
      - OUTPUT_LOCATION=/output

  http-gateway:
    container_name: http-rev-prox
    image: nginx
    ports:
      - '80:80'
    #- '443:443' configure https one day...
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./output:/static/output:ro
    depends_on:
      - script-server
