version: "3.7"

services:
# This can be accessed on localhost:8081/script/..., or within the docker network with script-server1:8081/script/...
  script-server:
    container_name: biab-script-server
    build:
      context: ./script-server/docker
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./script-server/:/home/node/app:rw
      - ./scripts:/scripts:r
      - ./output:/output:rw
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - SCRIPT_LOCATION=/scripts
      - OUTPUT_LOCATION=/output
      - NODE_ENV=development
      - R_LIBS_USER=/home/node/app/r-libs
    command: "npm start"

## UI server to use when you just want to use the UI
  ui-prod:
    container_name: biab-ui-prod
    build:
      context: ./ui
      dockerfile: Dockerfile.prod
    ports:
      - '8877:80'
    depends_on:
      - script-server

## UI server to use when developing UI code
  # ui:
  #   container_name: biab-ui
  #   build:
  #     context: ./ui
  #     dockerfile: Dockerfile
  #   user: "node"
  #   volumes:
  #     - './ui:/app:rw'
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true 
  #   depends_on:
  #     - script-server

  http-gateway:
    container_name: http-rev-prox
    image: nginx
    ports:
    - '80:80'
    #- '443:443' configure https one day...
    volumes:
    - ./http-proxy/conf.d-prod:/etc/nginx/conf.d:rw
    #- ./http-proxy/conf.d:/etc/nginx/conf.d:rw
    - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - ui
      - script-server

## Server to use when making changes to the OpenAPI specification
  # openapi_swagger:
  #   container_name: swagger_editor
  #   image: swaggerapi/swagger-editor
  #   # Swagger editor will be available at port :80 or https://localhost
  #   ports:
  #     - "81:8080"
  #   # Swagger File to feed the Swagger Editor
  #   # Base URL to point for consulting the Swagger https://localhost/swagger
  #   environment:
  #     SWAGGER_FILE: openapi.json
  #     BASE_URL: /swagger
  #   volumes:
  #     - ./script-server/api/:/app
  #   # depends_on:
  #   #   - script-server
