version: "3.7"

services:
  ### NodeJS server that was intended to call r-base with params
  # node:
  #   image: "node:17"
  #   user: "node"
  #   working_dir: /home/node/app
  #   environment:
  #     - NODE_ENV=production
  #   volumes:
  #     - ./node/:/home/node/app:r
  #   ports:
  #     - "8080"
  #   command: "npm start"

  ### This image can run a single script, but I could not launch it with parameters
  # stepr:
  #   image: r-base
  #   command: ["Rscript", "HelloWorld.R"]
  #   working_dir: "/usr/local/src/myscripts"
  #   volumes:
  #     - ./scripts:/usr/local/src/myscripts:r


   ### NodeJS server that was intended to call r-base with params
  r-server:
    image: "node:17"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./r-server/:/home/node/app:rw
    ports:
      - "8080:5000"
    environment:
      - PORT=5000
    command: "npm start"

  openapi_swagger:
    container_name: swagger_editor
    image: swaggerapi/swagger-editor
    # Swagger editor will be available at port :80 or https://localhost
    ports:
      - "80:8080"
    # Swagger File to feed the Swagger Editor
    # Base URL to point for consulting the Swagger https://localhost/swagger
    environment:
      SWAGGER_FILE: schema.json
      BASE_URL: /swagger
    volumes:
      - ./api/:/app
    depends_on:
      - r-server
