name: biab-env
channels:
  - conda-forge  # Mejor para paquetes de R y geo-dependencias
  - defaults
dependencies:
  # Python y herramientas básicas
  - python=3.8
  - pip
  - pip:
    - git+https://github.com/geo-bon/bon-in-a-box-pipeline-engine.git
    # O si usas el fork de PEM-Humboldt:
    # - git+https://github.com/PEM-Humboldt/biab-2.0.git

  # Paquetes de R esenciales para modelos de ocupación
  - r-base=4.1.3  # Versión exacta que tienes localmente
  - r-unmarked=1.2.5=*r41h*
  - r-lme4=1.1.35
  - r-sf=1.0.16
  - r-lme4
  - r-dplyr
  - r-tidyr
  - r-ggplot2
  - r-readr
  - r-raster      # Manejo de rasters (si usas covariables ambientales)

  # Dependencias geoespaciales (opcional, si trabajas con mapas)
  - gdal
  - proj
  - geos