# Script for analyzing ProtConn with the function
#packagesPrev<- installed.packages()[,"Package"] # Check and get a list of installed packages in this machine and R version # nolint
packagesList<-list("terra", "dplyr", "ggrepel", "rjson", "Makurhini")
#lapply(packagesList, function(x) {   if ( ! x %in% packagesPrev ) { install.packages(x, force=T)}    }) # Check and install required packages that are not previously installed # nolint
library(sf)
library(rmapshaper)
# Load libraries
lapply(packagesList, library, character.only = TRUE)  # Load libraries - packages
Sys.getenv("SCRIPT_LOCATION")

# The input file 'input.json' is generated by executing the 'Run Script' command in the ByB platform. # nolint
input <- biab_inputs() # Load input file

units::units_options(set_units_mode = "standard")
# Load study area shapefile
print("Loading polygons")
study_area <- st_read(input$study_area_polygon)#, crs=input$crs) #%>% sf::st_transform(input$studyarea_epsg) # load study area and transform using specified epsg
protected_area <- st_read(input$protected_area_polygon)#, input$crs) #%>% sf::st_transform(input$studyarea_epsg) # load protected areas and transform using specified epsg
print(str(protected_area))
protected_area <- protected_area[st_geometry_type(protected_area) %in% c("POLYGON", "MULTIPOLYGON"), ]

# make geometry valid
protected_area <- st_make_valid(protected_area)
# check if it is valid, and if not, apply buffer function
protected_area <- st_buffer(protected_area, 0)
# if it still isn't valid, try some other things
protected_area <- st_simplify(protected_area, dTolerance = 0.001)
protected_area <- st_set_precision(protected_area, 1e6)

print("Calculating ProtConn")
protected_area_filt <- protected_area %>% dplyr::filter(STATUS_YR <= input$years)

protconn_result <- Makurhini::MK_ProtConn(
  nodes=protected_area_filt,
  region=study_area,
  area_unit="m2",
  distance=list(type=input$distance_matrix_type),
  probability=0.5,
  transboundary=input$transboundary_distance,
  distance_thresholds=c(input$distance_threshold)
)

protconn_result <- as.data.frame(protconn_result)[c(2,3,4),c(3,4)]
protconn_result[is.na(protconn_result)] <- 0
print(protconn_result)

# Output protconn result
protconn_result_path <- file.path(outputFolder, "protconn_result.csv") # Define the file path for the 'val_wkt_path' output
write.csv(protconn_result, protconn_result_path, row.names = F ) # Write the 'val_wkt_path' output
biab_output("protconn_result", protconn_result_path)

result_plot <- ggplot2::ggplot(protconn_result) +
  geom_col(aes(y=Percentage, x=1, fill=`ProtConn indicator`)) +
  coord_polar(theta="y") +
  xlim(c(0, 1.5)) +
  geom_text(aes(y=Percentage, x=1, group=`ProtConn indicator`, label=paste0(round(Percentage, 2), "%")), position=position_stack(vjust=0.5))+
  scale_fill_manual(values=c("seagreen4", "seagreen1", "orchid4"))+
  theme_void() +
  theme(text=element_text(color="White"))

# output result plot
result_plot_path <- file.path(outputFolder, "result_plot.png") # save protconn result
ggsave(result_plot_path, result_plot, dpi=300, height=7, width=7)
biab_output("result_plot", result_plot_path)

# Change in protection over time
# Sequence with start year by interval
years <- seq(from=input$start_year, to=input$years, by=input$year_int)
years <- c(years, input$years)
# assign all PAs with no date to the start date for plotting
for(i in 1:nrow(protected_area)) {
  if(is.na(protected_area$STATUS_YR[i])){
    protected_area$STATUS_YR[i] <- input$start_year
  }
}
# Calculate ProtConn for each specified year
print("Calculating ProtConn time series")

protconn_ts_result <- list()

for (i in 1:length(years)) {
  print(years[i])
  protected_area_filt_yr <- protected_area %>% dplyr::filter(STATUS_YR <= years[i])
  if(nrow(protected_area_filt_yr)==0) {
    print(paste("No protected area data from", years, "beginning calculations at first year with data"))
    next
  } else {
    protconn_result <- Makurhini::MK_ProtConn(
      nodes=protected_area_filt_yr,
      region=study_area, area_unit="m2",
      distance=list(type=input$distance_matrix_type),
      probability=0.5,
      transboundary=input$transboundary_distance,
      distance_thresholds=c(input$distance_threshold)
    )
    print(protconn_result)
    protconn_result.df <- as.data.frame(protconn_result)[c(1,3,4),c(3,4)] %>% mutate(Year=years[i])
    protconn_ts_result[[i]] <- protconn_result.df
  }
}

print("Compiling time series")
result_yrs <- bind_rows(protconn_ts_result)
result_yrs[is.na(result_yrs)] <- 0
print(class(result_yrs))

result_yrs_path <- file.path(outputFolder, "result_yrs.csv") # save protconn result
write.csv(result_yrs, result_yrs_path)
biab_output("result_yrs", result_yrs_path)

xint <- min(result_yrs$Year) + 25
print(result_yrs)
result_yrs_plot <- ggplot(result_yrs, aes(x=Year, y=Percentage, group=`ProtConn indicator`, shape=`ProtConn indicator`, color=`ProtConn indicator`))+
  geom_point() +
  geom_line() +
  labs(y="Percent area", x="Year") +
  geom_hline(yintercept=30, lty=2) +
  annotate("text", x=xint, y=31, label="Kunming-Montreal target") +
  geom_line() +
  theme_classic()

result_yrs_plot_path <- file.path(outputFolder, "result_plot_yrs.png") # save protconn result with dispersal presets
ggsave(result_yrs_plot_path, result_yrs_plot)
biab_output("result_yrs_plot", result_yrs_plot_path)

print("Calculating ProtConn for three most common dispersal distances")
protconn_result_1km <- Makurhini::MK_ProtConn(nodes=protected_area_filt, region=study_area, area_unit="m2", distance=list(type=input$distance_matrix_type), probability=0.5,
transboundary=input$transboundary_distance, distance_thresholds=1000)
protconn_result_1km <- as.data.frame(protconn_result_1km)[c(2,3,4),c(3,4)]
protconn_result_1km[is.na(protconn_result_1km)] <- 0
protconn_result_1km$distance <- "1 km"

protconn_result_10km <- Makurhini::MK_ProtConn(nodes=protected_area_filt, region=study_area, area_unit="m2", distance=list(type=input$distance_matrix_type), probability=0.5,
transboundary=input$transboundary_distance, distance_thresholds=10000)
protconn_result_10km <- as.data.frame(protconn_result_10km)[c(2,3,4),c(3,4)]
protconn_result_10km[is.na(protconn_result_10km)] <- 0
protconn_result_10km$distance <- "10 km"

protconn_result_100km <- Makurhini::MK_ProtConn(nodes=protected_area_filt, region=study_area, area_unit="m2", distance=list(type=input$distance_matrix_type), probability=0.5,
transboundary=input$transboundary_distance, distance_thresholds=100000)
protconn_result_100km <- as.data.frame(protconn_result_100km)[c(2,3,4),c(3,4)]
protconn_result_100km[is.na(protconn_result_100km)] <- 0
protconn_result_100km$distance <- "100 km"

results_preset <- rbind.data.frame(protconn_result_1km, protconn_result_10km, protconn_result_100km)

result_preset_plot <- ggplot2::ggplot(results_preset) +
  geom_col(aes(y=Percentage, x=1, fill=`ProtConn indicator`)) +
  coord_polar(theta="y") +
  xlim(c(0, 1.5)) +
  geom_text(aes(y=Percentage, x=1, group=`ProtConn indicator`, label=paste0(round(Percentage, 2), "%")), position=position_stack(vjust=0.5)) +
  scale_fill_manual(values=c("seagreen4", "seagreen1", "orchid4")) +
  facet_wrap(~distance) +
  theme_void() +
  theme(text=element_text(color="White"))

# output
result_plot_preset_path <- file.path(outputFolder, "result_preset_plot.png")
ggsave(filename=result_plot_preset_path, plot=result_preset_plot, dpi=300, height=8, width=12)
biab_output("result_preset_plot", result_plot_preset_path)


