#### Load required packages - libraries to run the script ####

# Install necessary libraries - packages  
packagesPrev<- installed.packages()[,"Package"] # Check and get a list of installed packages in this machine and R version
packagesNeed<- list("magrittr", "terra", "raster", "sf", "pbapply", "this.path", "rjson", "gdalcubes") # Define the list of required packages to run the script
lapply(packagesNeed, function(x) {   if ( ! x %in% packagesPrev ) { install.packages(x, force=T)}    }) # Check and install required packages that are not previously installed

# Load libraries
packagesList<-list("magrittr", "terra", "gdalcubes") # Explicitly list the required packages throughout the entire routine. Explicitly listing the required packages throughout the routine ensures that only the necessary packages are listed. Unlike 'packagesNeed', this list includes packages with functions that cannot be directly called using the '::' syntax. By using '::', specific functions or objects from a package can be accessed directly without loading the entire package. Loading an entire package involves loading all the functions and objects 
lapply(packagesList, library, character.only = TRUE)  # Load libraries - packages  


#### Set enviroment variables ####

# Set the 'outputFolder' environment variables
# The environment variable refers to the path of the output folder for the entire routine
# 'outputFolder' allows interaction with the output folder of the routine and access to nearby paths, such as the input folder ('input')

# There are two options to set 'outputFolder'
# Please select only one of the two options, while silencing the other with the '#' syntaxis: 

# Option 1: Setting for production pipeline purposes. This is designed for use in a production environment or workflow.
Sys.setenv(outputFolder = "/path/to/output/folder")

# Option 2: Recommended for debugging purposes to be used as a testing environment. This is designed to facilitate script testing and correction
if ( (!exists("outputFolder"))  ) {
  outputFolder<- {x<- this.path::this.path();  file_prev<-  paste0(gsub("/scripts.*", "/output", x), gsub("^.*/scripts", "", x)  ); options<- tools::file_path_sans_ext(file_prev) %>% {c(., paste0(., ".R"), paste0(., "_R"))}; folder_out<- options %>% {.[file.exists(.)]} %>% {.[which.max(sapply(., function(info) file.info(info)$mtime))]}; folder_final<- list.files(folder_out, full.names = T) %>% {.[which.max(sapply(., function(info) file.info(info)$mtime))]} }
}

# Set the 'input' environment variables. The 'input' environment contains the specified inputs from the ByB platform.
# The input file 'input.json' is generated by executing the 'Run Script' command in the ByB platform.
input <- rjson::fromJSON(file=file.path(outputFolder, "input.json")) # Load input file

# This section adjusts the input values based on specific conditions to rectify and prevent errors in the input paths
input<- lapply(input, function(x) { if (!is.null(x) && length(x) > 0 && grepl("/", x) && !grepl("http://", x)  ) { 
  sub("/output/.*", "/output", outputFolder) %>% dirname() %>%  file.path(x) %>% {gsub("//+", "/", .)}  } else{x} }) 


####  Script body ####
output<- (function(){

# Cargar area de estudio 
study_area<- terra::rast(input$studyarea_grid) %>% terra::project(terra::crs( "+proj=longlat +datum=WGS84 +no_defs" )) # cargar raster
box_study_area <-  sf::st_bbox(study_area) # estimar extension
crs_polygon<- terra::crs( study_area ) %>% as.character() # estimar proyeccion del poligono
res_studyarea<- terra::res(study_area)



# revisar si la url de la coleccion existe
test_url<- tryCatch({httr::GET(input$RSTACQuery)}, error= function(e) {NULL})
if(is.null(test_url)){return("No se pudo acceder a la url servidor stac")} # mensaje, la url no existe

# Cargar coleccion
RSTACQuery<- rstac::stac(input$RSTACQuery)
STACItemCollection <- rstac::stac_search(q= RSTACQuery, collections = input$RSTACcollection  , 
                                         bbox = box_study_area) %>% rstac::get_request()

# ajustar roles de la coleccion
for (i in 1:length(STACItemCollection$features)){ STACItemCollection$features[[i]]$assets[[1]]$roles<-'data'}

# especificar las variables asset de las colecciones a cargar
assests_all<- unlist(rstac::items_assets(STACItemCollection))
assets<-   if( input$RSTACassets == "allVars"){ assests_all } else {  
  selectVars<- input$selectVars %>% strsplit( ",\\s*") %>% unlist() %>% trimws()
  assests_all[assests_all %in% selectVars] }
if(length(assets)<1){return("Los assets no corresponden")}

# Cargar image coleccion
image_collection <- gdalcubes::stac_image_collection(s=STACItemCollection$features, 
                                                     asset_names = assets,
                                                     srs = crs_polygon
                                                     )


# Definir ventana temporal
if(is.null(input$time_period)){
  t0<- gdalcubes::extent(image_collection)$t0
  t1<- gdalcubes::extent(image_collection)$t1
} else {
  time_period<- input$time_period %>% strsplit( ",\\s*") %>% unlist() %>% trimws() %>% as.Date(format = "%Y-%m-%d")
  t0<- time_period %>% min()
  t1<- time_period %>% max()
}


cube_collection<- gdalcubes::cube_view(srs = crs_polygon,  extent = list(t0 = t0, t1 = t1,
                                                                         left = box_study_area[1], right = box_study_area[3],
                                                                         top = box_study_area[4], bottom = box_study_area[2]),
                                       dx = res_studyarea[1], dy = res_studyarea[2], dt = input$time_zonal, aggregation = "first", resampling = "first",
                                       keep.asp= F)


cube <- gdalcubes::raster_cube(image_collection, cube_collection)


# Descargar cubo
fn = tempfile(fileext = ".nc"); gdalcubes::write_ncdf(cube, fn)
nc <-  ncdf4::nc_open(fn); vars <- names(nc$var)

cube_times<- as.data.frame(gdalcubes::dimension_bounds(cube)[["t"]])

nc_times<- if(nrow(cube_times)<2){"X0"}else{ paste0("X", ncdf4::ncvar_get(nc, "time_bnds")[1,]) }
time_collection<- as.data.frame(gdalcubes::dimension_bounds(cube)[["t"]]) %>% dplyr::mutate(time_id= nc_times, dim3=seq(nrow(.)))


terra_mask<- pbapply::pblapply(vars[5:length(vars)], function(x){ print(x)
  
  # Dimensiones de la capa
  dims_var <- ncdf4::ncvar_get(nc, x)
  
  # Validar si la capa esta vacia
  key<-  as.data.frame(which(!is.na(dims_var),  arr.ind = TRUE))

  if(nrow(key)>0){
    
    # Cargar capa raster
    key2<- {if(nrow(cube_times)<2){ dplyr::mutate(key, time_id= "X0") }else{ key }} %>% {list(., time_collection)} %>% plyr::join_all()
    brick  <- raster::brick(fn, var= x) %>% terra::rast() %>% terra::mask(study_area)
    
    test_brick<- terra::freq(brick)$value %>% min(na.rm = T)
    
    if(!test_brick %in% c(NA, Inf)){
    
    times<- unique(key2$time_id) 
    layer <- brick[[ times ]];
  
    
    # Organizar informacion de la capa
    info_layer<- dplyr::distinct(key2[, c("start", "end")]) %>% dplyr::distinct() %>% 
      dplyr::mutate(period= paste(start, end, sep="_"), layer= x) %>% 
      dplyr::mutate(layer= gsub( "[[:punct:]]", "_", paste(x, period, sep = "_") ) ) %>% 
      dplyr::mutate(file= paste0(layer, ".tif") ) %>% 
      dplyr::relocate("layer", .before = 1)

    # Organizar nombre de la capa
    names(layer)<- info_layer$layer

    list(layer=layer, info_layer= info_layer)
    } else {NULL}
  } else {NULL}
  
})  %>% {Filter(function(x) !is.null(x), .)} 


terra_mask_layers<- purrr::map(terra_mask, "layer") %>% setNames(unlist(lapply(., function(x) names(x))))



dir_stack<- file.path(outputFolder, "dir_stack")
unlink(dir_stack, recursive = TRUE); dir.create(dir_stack); setwd(dir_stack)

setwd(dir_stack)
output_layers<- lapply(terra_mask_layers, function(x){
  name_layer<- file.path(dir_stack, paste0(names(x), ".tif"))
  terra::writeRaster(x, name_layer, gdal=c("COMPRESS=DEFLATE", "TFW=YES"),  filetype = "GTiff", overwrite = TRUE );
  name_layer}) 



output<- list(list_vars= paste0(names(terra_mask_layers), collapse = ", "), dir_stack= dir_stack, first_var= as.character(output_layers[1]) )


})()









#### Outputing result to JSON ####

# Write the output list to the 'output.json' file in JSON format
setwd(outputFolder)
jsonlite::write_json(output, file.path(outputFolder, "output.json"), auto_unbox = TRUE, pretty = TRUE)