#### Load required packages - libraries to run the script ####

# Install necessary libraries - packages  
packagesPrev<- installed.packages()[,"Package"] # Check and get a list of installed packages in this machine and R version
packagesNeed<- list("magrittr", "terra", "raster", "sf", "fasterize", "pbapply", "this.path", "rjson") # Define the list of required packages to run the script
lapply(packagesNeed, function(x) {   if ( ! x %in% packagesPrev ) { install.packages(x, force=T)}    }) # Check and install required packages that are not previously installed

# Load libraries
packagesList<-list("magrittr", "terra") # Explicitly list the required packages throughout the entire routine. Explicitly listing the required packages throughout the routine ensures that only the necessary packages are listed. Unlike 'packagesNeed', this list includes packages with functions that cannot be directly called using the '::' syntax. By using '::', specific functions or objects from a package can be accessed directly without loading the entire package. Loading an entire package involves loading all the functions and objects 
lapply(packagesList, library, character.only = TRUE)  # Load libraries - packages  


#### Set enviroment variables ####

# Set the 'outputFolder' environment variables
# The environment variable refers to the path of the output folder for the entire routine
# 'outputFolder' allows interaction with the output folder of the routine and access to nearby paths, such as the input folder ('input')

# There are two options to set 'outputFolder'
# Please select only one of the two options, while silencing the other with the '#' syntaxis: 

# Option 1: Setting for production pipeline purposes. This is designed for use in a production environment or workflow.
 Sys.getenv("SCRIPT_LOCATION")

# Option 2: Recommended for debugging purposes to be used as a testing environment. This is designed to facilitate script testing and correction
# outputFolder<- {x<- this.path::this.path();  file_prev<-  paste0(gsub("/scripts.*", "/output", x), gsub("^.*/scripts", "", x)  ); options<- tools::file_path_sans_ext(file_prev) %>% {c(., paste0(., ".R"), paste0(., "_R"))}; folder_out<- options %>% {.[file.exists(.)]} %>% {.[which.max(sapply(., function(info) file.info(info)$mtime))]}; folder_final<- list.files(folder_out, full.names = T) %>% {.[which.max(sapply(., function(info) file.info(info)$mtime))]} }



# Set the 'input' environment variables. The 'input' environment contains the specified inputs from the ByB platform.
# The input file 'input.json' is generated by executing the 'Run Script' command in the ByB platform.
input <- rjson::fromJSON(file=file.path(outputFolder, "input.json")) # Load input file

# This section adjusts the input values based on specific conditions to rectify and prevent errors in the input paths
input<- lapply(input, function(x) if( grepl("/", x) ){
  sub("/output/.*", "/output", outputFolder) %>% dirname() %>%  file.path(x) %>% {gsub("//+", "/", .)}  }else{x} ) # adjust input 1


####  Script body ####
output<- tryCatch({
 
# Load and convert the study area to aggregate polygon limits and project it to the defined EPSG coordinate system
vector_polygon<-  terra::vect(input$studyarea_path) %>% terra::aggregate()  %>%  terra::project( raster::crs( paste0("+init=epsg:", input$studyarea_EPSG) )    )
# Generate WKT representation of the strudy area polygon
wkt_polygon <- terra::geom(vector_polygon, wkt=TRUE) %>% {  paste0( "MULTIPOLYGON (",paste(gsub("POLYGON |MULTIPOLYGON ", "", .), collapse=  ", "),")") %>% {gsub("\\({4}", "\\(\\(\\(", .)}  }

# Convert the vector polygon to the GeoJSON format and transform its coordinate reference system to 4326 (WGS84) to make it compatible with the Leaflet interactive JavaScript library
geojson_polygon<- sf::st_as_sf(vector_polygon) %>% sf::st_transform(4326)


# Define and export the output values

# Define val_wkt_path output
dir_wkt<- file.path(outputFolder, "wkt_polygon_test.txt") # Define the file path for the 'val_wkt_path' output
writeLines(wkt_polygon, dir_wkt ) # Write the 'val_wkt_path' output

# Define val_studyarea_GeoJSON_path output
dir_GeoJSON<- file.path(outputFolder, "wkt_polygon_test.geojson") # Define the file path for the 'val_studyarea_GeoJSON_path' output
sf::st_write(geojson_polygon, dir_GeoJSON, overwrite=T, append=T) # Write the 'val_studyarea_GeoJSON_path' output

# Define final output list
output<- list(val_wkt_path= dir_wkt,val_studyarea_GeoJSON_path= dir_GeoJSON, val_studyarea_EPSG= input$studyarea_EPSG)

}, error = function(e) { list(error= conditionMessage(e)) })



#### Outputing result to JSON ####
# Write the output list to the 'output.json' file in JSON format
setwd(outputFolder)
jsonlite::write_json(output, "output.json", auto_unbox = TRUE, pretty = TRUE)