# Load required packages - libraries to run the script ####

## Check and install necessary libraries - packages  ####
packagesPrev<- installed.packages()[,"Package"] # Check and get a list of installed packages in this machine and R version
packagesNeed<- c("magrittr", "dplyr" , "this.path", "rjson", "sf", "raster", "pbapply", "ggplot2", "ggpubr"); packagesNeed<- packagesNeed[!packagesNeed==""] # Define the list of required packages to run the script
new.packages <- packagesNeed[!(packagesNeed %in% packagesPrev)]; if(length(new.packages)) {install.packages(new.packages, binary=T, force=T, dependencies = F, repos= "https://packagemanager.posit.co/cran/__linux__/jammy/latest")} # Check and install required packages that are not previously installed
packagesRemotes<- c(""); packagesRemotes<- packagesRemotes[!packagesRemotes==""] # Define the list of required packages to run that are avaliable from other sources
new.packagesRemotes <- packagesRemotes[!(packagesRemotes %in% packagesPrev)]; if(length(packagesRemotes)) {lapply(packagesRemotes, function(x) devtools::install_github(x))} # Check and install required packages that are not previously installed

## Load the necessary libraries into the script environment ####
packagesList<-list("magrittr", "terra", "raster", "ggplot2") # Explicitly list the required packages throughout the entire routine. Explicitly listing the required packages throughout the routine ensures that only the necessary packages are listed. Unlike 'packagesNeed', this list includes packages with functions that cannot be directly called using the '::' syntax. By using '::', specific functions or objects from a package can be accessed directly without loading the entire package. Loading an entire package involves loading all the functions and objects 
lapply(packagesList, library, character.only = TRUE)  # Load libraries - packages  


# Set enviroment variables ####

### Define output folder path ####
#### Option 1: Setting for production pipeline purposes. ####
##### This is designed for use in a production environment or workflow.
Sys.setenv(outputFolder = "/path/to/output/folder")

#### Option 2: Recommended for debugging purposes to be used as a testing environment. ####
##### This is designed to facilitate script testing and correction
if ( (!exists("outputFolder"))  ) {
  outputFolder<- {x<- this.path::this.path();  file_prev<-  paste0(gsub("/scripts.*", "/output", x), gsub("^.*/scripts", "", x)  ); options<- tools::file_path_sans_ext(file_prev) %>% {c(., paste0(., ".R"), paste0(., "_R"))}; folder_out<- options %>% {.[file.exists(.)]} %>% {.[which.max(sapply(., function(info) file.info(info)$mtime))]}; folder_final<- list.files(folder_out, full.names = T) %>% {.[which.max(sapply(., function(info) file.info(info)$mtime))]} }
}

### Define input folder path ####
#### Set the 'input' environment variables. The 'input' environment contains the specified inputs from the ByB platform.
#### The input file 'input.json' is generated by executing the 'Run Script' command in the ByB platform.
input <- rjson::fromJSON(file=file.path(outputFolder, "input.json")) # Load input file

#### Adjusts the input values paths ####
##### This section adjusts the input values based on specific conditions to rectify and prevent errors in the input paths
input<- lapply(input, function(x) { if (!is.null(x) && length(x) > 0 && grepl("/", x) && !grepl("http://", x)  ) { 
  sub("/output/.*", "/output", outputFolder) %>% dirname() %>%  file.path(x) %>% {gsub("//+", "/", .)}  } else{x} }) 




library(terra)
folder_adjustLayers<- file.path(outputFolder, "adjustLayers"); dir.create(folder_adjustLayers)

a<- file.path(dirname(input$grid_polygon), "IHEH_2022_1.tif")
b<- file.path(dirname(input$grid_polygon), "IHEH_2022_1.tif")


list_layers_adjust<- list(a= a, b= b)

### Write layers ####

#### Organize Stac layers ####
folder_adjustLayers<- file.path(outputFolder, "adjustLayers"); dir.create(folder_adjustLayers)
layer_paths<-c()
for (i in 1:2) {
  
  layer_path <- file.path(folder_adjustLayers, names(list_layers_adjust)[i] ) %>% paste0(".tif")
  terra::writeRaster(terra::rast(list_layers_adjust[[i]]), layer_path, overwrite = TRUE ) # write result
  
  fp <- paste0(layer_path[1])
  layer_paths <- cbind(layer_paths,fp)
}





# Define final output list
output<- list(rasters= layer_paths)


#### Outputing result to JSON ####

# Write the output list to the 'output.json' file in JSON format
setwd(outputFolder)
jsonData <- rjson::toJSON(output, indent=2)
write(jsonData, file.path(outputFolder,"output.json"))