/*
 * BON in a Box - Script service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jean-michel.lord@mcgill.ca
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BonInABoxScriptService);
  }
}(this, function(expect, BonInABoxScriptService) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BonInABoxScriptService.DefaultApi();
  });

  describe('(package)', function() {
    describe('DefaultApi', function() {
      describe('getScriptInfo', function() {
        it('should call getScriptInfo successfully', function(done) {
          // TODO: uncomment, update parameter values for getScriptInfo call and complete the assertions
          /*

          instance.getScriptInfo(scriptPath, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(&#x27;string&#x27;);
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('runScript', function() {
        it('should call runScript successfully', function(done) {
          // TODO: uncomment, update parameter values for runScript call and complete the assertions
          /*
          var opts = {};

          instance.runScript(scriptPath, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(BonInABoxScriptService.InlineResponse200);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
