FROM gradle:7.5.1-jdk11

#INSTALL DOCKER CLI
ENV DOCKER_VERSION=20.10.9
RUN curl -sfL -o docker.tgz "https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKER_VERSION}.tgz" && \
  tar -xzf docker.tgz docker/docker --strip=1 && \
  mv docker /usr/local/bin && \
  rm docker.tgz

RUN curl -L "https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
RUN chmod +x /usr/local/bin/docker-compose
RUN chmod +x /usr/local/bin/docker


RUN set -ex; \
    apt-get update; \
    apt-get install -y --no-install-recommends python3 libc6-dev; \
    apt-get clean all;

RUN echo "dev" > /version.txt 