## Environment variables available
# Script location can be used to access other scripts
print(Sys.getenv("SCRIPT_LOCATION"))

## Install required packages
packages <- c("rgbif", "rjson", "raster", "dplyr", "stringr")
new.packages <- packages[!(packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)

## Load required packages
library("rgbif")
library("dplyr")
library("raster")
library("rjson")
library("stringr")

## Load functions
source("D:/Repositorios/biab-2.0/scripts/data/getObservationsFunc.R")
source("D:/Repositorios/biab-2.0/scripts/SDM/sdmUtils.R")




# Set up the working environment ####

## Set output folder ####
# Option 1: Setting for production pipeline purposes. This is designed for use in a production environment or workflow.
Sys.setenv(outputFolder = "/path/to/output/folder")

# Option 2: Recommended for debugging purposes to be used as a testing environment. This is designed to facilitate script testing and correction
if ( (!exists("outputFolder"))  ) {
  outputFolder<- {x<- this.path::this.path();  file_prev<-  paste0(gsub("/scripts.*", "/output", x), gsub("^.*/scripts", "", x)  ); options<- tools::file_path_sans_ext(file_prev) %>% {c(., paste0(., ".R"), paste0(., "_R"))}; folder_out<- options %>% {.[file.exists(.)]} %>% {.[which.max(sapply(., function(info) file.info(info)$mtime))]}; folder_final<- list.files(folder_out, full.names = T) %>% {.[which.max(sapply(., function(info) file.info(info)$mtime))]} }
}

## Set input folder ####
# Set the 'input' environment variables. The 'input' environment contains the specified inputs from the ByB platform. The input file 'input.json' is generated by executing the 'Run Script' command in the ByB platform.
input <- rjson::fromJSON(file=file.path(outputFolder, "input.json")) # Load input file

# This lines adjusts the input values based on specific conditions to rectify and prevent errors in the input paths
input<- lapply(input, function(y) lapply(y, function(x)  { if (!is.null(x) && length(x) > 0 && grepl("/", x) && !grepl("http://", x)  ) { 
  sub("/output/.*", "/output", outputFolder) %>% dirname() %>%  file.path(x) %>% {gsub("//+", "/", .)}  } else{x} }) %>% unlist()) 





input <- fromJSON(file=file.path(outputFolder, "input.json"))
print("Inputs: ")
print(input)


# Tranform the vector to a bbox object
bbox_wgs84 <- sf::st_bbox(c(xmin = input$bbox[1], ymin = input$bbox[2], 
            xmax = input$bbox[3], ymax = input$bbox[4]), crs = sf::st_crs(input$proj)) %>% sf::st_as_sfc() %>% sf::st_transform(crs = "EPSG:4326") %>% 
        sf::st_bbox()

country <- input$country
if (!is.null(country) && nchar(country) < 2) {
  print("Invalid country")
  country <- NULL
}

bbox_buffer <- input$bbox_buffer
if (is.null(bbox_buffer)) {
  bbox_buffer <- 0
}

occurrence_status <- str_split(input$occurrence_status, " ")[[1]]

# Loading data from GBIF (https://www.gbif.org/)
obs <- get_observations(database = "gbif", 
  species = input$species,
           year_start = input$year_start,
           year_end = input$year_end,
           country = country,
           bbox = bbox_wgs84,
           occurrence_status = occurrence_status,
           limit = input$limit)

# Creating the bbox
  obs_pts <- stacatalogue::project_coords(obs,
                            lon = "decimal_longitude",
                            lat = "decimal_latitude",
                            proj_from = "+proj=longlat +datum=WGS84",
                            proj_to = input$proj)
bbox <- stacatalogue::points_to_bbox(obs_pts, buffer = bbox_buffer)
bbox <-c(bbox$xmin, bbox$ymin, bbox$xmax, bbox$ymax)

# Outputs
obs.data <- file.path(outputFolder, "obs_data.tsv")
write.table(obs, obs.data,
             append = F, row.names = F, col.names = T, sep = "\t")

obs.bbox <- file.path(outputFolder, "obs_bbox.tsv")
write.table(bbox, obs.bbox,
             append = F, row.names = F, col.names = T, sep = "\t")
  output <- list(
                  "n_presence" =  nrow(obs),
                  "presence" = obs.data,
                  "bbox" = obs.bbox
                  ) 
  jsonData <- toJSON(output, indent=2)
  write(jsonData, file.path(outputFolder,"output.json"))
  
