#### Load required packages - libraries to run the script ####

# Install necessary libraries - packages  
packagesPrev<- installed.packages()[,"Package"] # Check and get a list of installed packages in this machine and R version
packagesNeed<- list("magrittr", "terra", "raster", "sf", "fasterize", "pbapply", "this.path", "rjson") # Define the list of required packages to run the script
lapply(packagesNeed, function(x) {   if ( ! x %in% packagesPrev ) { install.packages(x, force=T)}    }) # Check and install required packages that are not previously installed

# Load libraries
packagesList<-list("magrittr", "terra") # Explicitly list the required packages throughout the entire routine. Explicitly listing the required packages throughout the routine ensures that only the necessary packages are listed. Unlike 'packagesNeed', this list includes packages with functions that cannot be directly called using the '::' syntax. By using '::', specific functions or objects from a package can be accessed directly without loading the entire package. Loading an entire package involves loading all the functions and objects 
lapply(packagesList, library, character.only = TRUE)  # Load libraries - packages  


#### Set enviroment variables ####

# Set the 'outputFolder' environment variables
# The environment variable refers to the path of the output folder for the entire routine
# 'outputFolder' allows interaction with the output folder of the routine and access to nearby paths, such as the input folder ('input')

# There are two options to set 'outputFolder'
# Please select only one of the two options, while silencing the other with the '#' syntaxis: 

# Option 1: Setting for production pipeline purposes. This is designed for use in a production environment or workflow.
Sys.getenv("SCRIPT_LOCATION")

# Option 2: Recommended for debugging purposes to be used as a testing environment. This is designed to facilitate script testing and correction
# outputFolder<- {x<- this.path::this.path();  file_prev<-  paste0(gsub("/scripts.*", "/output", x), gsub("^.*/scripts", "", x)  ); options<- tools::file_path_sans_ext(file_prev) %>% {c(paste0(., ".R"), paste0(., "_R"))}; folder_out<- options %>% {.[file.exists(.)]} %>% {.[which.max(sapply(., function(info) file.info(info)$mtime))]}; folder_final<- list.files(folder_out, full.names = T) %>% {.[which.max(sapply(., function(info) file.info(info)$mtime))]} }




# Set the 'input' environment variables. The 'input' environment contains the specified inputs from the ByB platform.
# The input file 'input.json' is generated by executing the 'Run Script' command in the ByB platform.
input <- rjson::fromJSON(file=file.path(outputFolder, "input.json")) # Load input file

# This section adjusts the input values based on specific conditions to rectify and prevent errors in the input paths
input<- lapply(input, function(x) if( grepl("/", x) ){
  sub("/output/.*", "/output", outputFolder) %>% dirname() %>%  file.path(x) %>% {gsub("//+", "/", .)}  }else{x} ) # adjust input 1



####  Script body ####
output<- tryCatch({
  
  study_area<- terra::rast(input$studyarea_grid)
  
  # Cargar coleccion

    RSTACQuery<- rstac::stac("http://io.biodiversite-quebec.ca/stac/")
    box_study_area <-  sf::st_bbox(study_area)
    crs_polygon<- terra::crs( study_area ) %>% as.character()
    dim_study_area<- dim(study_area)
    
    STACItemCollection <- rstac::stac_search(q= RSTACQuery, collections = "earthenv_topography"  , bbox = box_study_area) %>% rstac::get_request()

    for (i in 1:length(STACItemCollection$features)) {
      feature <- STACItemCollection$features[[i]]
      asset_name <- names(feature$assets)[1]  # Obtener el nombre del primer asset
      new_name <- feature$id  # Utilizar el ID de la feature como nuevo nombre
      names(STACItemCollection$features[[i]]$assets)<- new_name
    }
    
    
    assets<- unlist(lapply(STACItemCollection$features,function(y){names(y$assets)})) %>% unique()
    
    image_collection <- gdalcubes::stac_image_collection(STACItemCollection$features, asset_names = "elevation" )
    
    
    t0<- gdalcubes::extent(image_collection)$t0
    t1<- gdalcubes::extent(image_collection)$t1
    
    cube_collection<- gdalcubes::cube_view(srs = crs_polygon,  extent = list(t0 = t0, t1 = t1,
                                                                             left = box_study_area[1], right = box_study_area[3],
                                                                             top = box_study_area[4], bottom = box_study_area[2]),
                                           nx = dim_study_area[1], ny = dim_study_area[2], dt = "P1Y",aggregation = "near", resampling = "first",
                                           keep.asp= F)

    cube <- gdalcubes::raster_cube(image_collection, cube_collection)
  
    
    
    # Descargar cubo
    fn = tempfile(fileext = ".nc"); gdalcubes::write_ncdf(cube, fn)
    nc <-  ncdf4::nc_open(fn); vars <- names(nc$var)
    
    # Ordenar temporalidad del cubo
    cube_times<- as.data.frame(gdalcubes::dimension_bounds(cube)[["t"]])
    cube_times
    
    nc_times<- if(nrow(cube_times)<2){"X0"}else{ paste0("X", ncdf4::ncvar_get(nc, "time_bnds")[1,]) }
    time_collection<- as.data.frame(gdalcubes::dimension_bounds(cube)[["t"]]) %>%
      dplyr::mutate(time_id= nc_times, dim3=seq(nrow(.)), period= paste0(start, "-", end))
    
    terra_mask<- pbapply::pblapply(vars[5:length(vars)], function(x){ print(x)
      
      # Dimensiones de la capa
      dims_var <- ncdf4::ncvar_get(nc= nc, varid= x, collapse_degen = F)
      if(dim(dims_var)[1]!= dim_study_area[1]){dims_var<- t(dims_var)}

      # Validar si la capa esta vacia
      key<-  as.data.frame(which(!is.na(dims_var),  arr.ind = TRUE))
      
      if(nrow(key)>0){
        
        # Cargar capa raster
        key2<- {if(nrow(cube_times)<2){ dplyr::mutate(key, time_id= "X0") }else{ key }} %>% {list(., time_collection)} %>% plyr::join_all()
        
        stack_var<-  terra::rast(dims_var) %>% setNames(nc_times) 
        terra::crs(stack_var)<- terra::crs(study_area)
        terra::ext(stack_var)<- terra::ext(study_area)

        times<- unique(key2$time_id) 
        layer <-   stack_var  [[ times ]] %>% terra::mask(study_area) %>% setNames(paste0(x, unique(key2$period)))
        
      } else {NULL}
      
    })  %>% {Filter(function(x) !is.null(x), .)}
    
    
    dir_stack<- file.path(outputFolder, "dir_stack")
    unlink(dir_stack, recursive = TRUE); dir.create(dir_stack); setwd(dir_stack)
    
    
    setwd(dir_stack)
    lapply(terra_mask, function(x)
      terra::writeRaster(x, paste0(names(x), ".tif"), gdal=c("COMPRESS=DEFLATE", "TFW=YES"),  filetype = "GTiff", overwrite = TRUE ))
    
    output<- list(dir_stack= dir_stack)
  
}, error = function(e) { list(error= conditionMessage(e)) })




#### Outputing result to JSON ####

# Write the output list to the 'output.json' file in JSON format
setwd(outputFolder)
jsonlite::write_json(output, "output.json", auto_unbox = TRUE, pretty = TRUE)