
# Set session parameters ####

## Load libraries to run the script ####

### Check and Install necessary libraries ####
options(devtools.ask = FALSE)
packagesPrev<- installed.packages()[,"Package"] # Check and get a list of installed packages in this machine and R version
packagesNeed<- c("magrittr", "this.path", "rjson", "data.table", "dplyr", "terra", "raster",  "sf", "stars", "rgdal", "remotes", "RCurl", "devtools", "stringr", "sp") # Define the list of required packages to run the script
new.packages <- packagesNeed[!(packagesNeed %in% packagesPrev)]; if(length(new.packages)) {install.packages(new.packages, binary=T, force=T, dependencies = F, repos= "https://packagemanager.posit.co/cran/__linux__/jammy/latest")} # Check and install required packages that are not previously installed

if (!"stacatalogue" %in% packagesPrev) devtools::install_github("ReseauBiodiversiteQuebec/stac-catalogue")
if (!"gdalcubes" %in% packagesPrev) devtools::install_github("appelmar/gdalcubes_R")


### Load libraries ####
packagesList<-list("magrittr", "terra", "raster", "gdalcubes") # Explicitly list the required packages throughout the entire routine. Explicitly listing the required packages throughout the routine ensures that only the necessary packages are listed. Unlike 'packagesNeed', this list includes packages with functions that cannot be directly called using the '::' syntax. By using '::', specific functions or objects from a package can be accessed directly without loading the entire package. Loading an entire package involves loading all the functions and objects 
lapply(packagesList, library, character.only = TRUE)  # Load libraries - packages  



# Set up the working environment ####

## Set output folder ####
# Option 1: Setting for production pipeline purposes. This is designed for use in a production environment or workflow.
Sys.setenv(outputFolder = "/path/to/output/folder")

# Option 2: Recommended for debugging purposes to be used as a testing environment. This is designed to facilitate script testing and correction
if ( (!exists("outputFolder"))  ) {
  outputFolder<- {x<- this.path::this.path();  file_prev<-  paste0(gsub("/scripts.*", "/output", x), gsub("^.*/scripts", "", x)  ); options<- tools::file_path_sans_ext(file_prev) %>% {c(., paste0(., ".R"), paste0(., "_R"))}; folder_out<- options %>% {.[file.exists(.)]} %>% {.[which.max(sapply(., function(info) file.info(info)$mtime))]}; folder_final<- list.files(folder_out, full.names = T) %>% {.[which.max(sapply(., function(info) file.info(info)$mtime))]} }
}

## Set input folder ####
# Set the 'input' environment variables. The 'input' environment contains the specified inputs from the ByB platform. The input file 'input.json' is generated by executing the 'Run Script' command in the ByB platform.
input <- rjson::fromJSON(file=file.path(outputFolder, "input.json")) # Load input file

# This lines adjusts the input values based on specific conditions to rectify and prevent errors in the input paths
input<- lapply(input, function(y) lapply(y, function(x)  { if (!is.null(x) && length(x) > 0 && grepl("/", x) && !grepl("http", x)  ) { 
  sub("/output/.*", "/output", outputFolder) %>% dirname() %>%  file.path(x) %>% {gsub("//+", "/", .)}  } else{x} }) %>% unlist()) 


#  Script body ####



  data_points<- sf::st_read(input$spatial_points) %>% dplyr::mutate(id_row=seq(nrow(.))) 
  layers_covs<- list.files(input$folder_vars, "\\.tif$", recursive = TRUE, full.names = TRUE)
  
  
  stack_vars<- terra::rast(layers_covs) %>% setNames(tools::file_path_sans_ext(basename(layers_covs)))
  base_grid<- stack_vars[[1]] %>% terra::rast() %>% terra::setValues(seq(ncell(.))) %>% terra::mask(min(stack_vars)) %>% setNames("ID_grid")
    
  stack_vars<- c(base_grid, stack_vars)
  
  data_points2<- data_points %>% cbind(setNames(as.data.frame(sf::st_coordinates(.)), c("X_coord", "Y_coord"))) %>% dplyr::mutate(id_coord= as.numeric(factor(paste0(X_coord, Y_coord)))) 
  
  distinct_id_coord <- data_points2 %>% dplyr::filter(!duplicated(id_coord)) %>% dplyr::select(id_coord)
  
  
  # Generar matriz pixeles por puntos y covariables
  covars_ID<-  raster::extract(stack_vars, distinct_id_coord) %>% {.[,2:length(.)]} %>% 
    dplyr::mutate(id_coord= distinct_id_coord$id_coord)

  join_covars<- covars_ID %>% list(as.data.frame(data_points2)) %>% plyr::join_all() %>% 
    dplyr::select(-c("id_row", "id_coord")) %>% dplyr::filter(!is.na(ID_grid))
  

  
  # Salida final
  spatial_covars<- sf::st_as_sf(join_covars)
  data_covars<- sf::st_drop_geometry(spatial_covars)
  
  data_covars_path<- file.path(outputFolder, "vars_dataset.csv") # Define the file path for the 'val_wkt_path' output
  write.csv(data_covars, data_covars_path, row.names = F, sep= ";" ) # Write the 'val_wkt_path' output
  
  
  
  spatial_covars_path<- file.path(outputFolder, "spatial_covars.GeoJSON") # Define the file path for the 'val_wkt_path' output
  sf::st_write(spatial_covars, spatial_covars_path, delete_dsn= T, driver = "GeoJSON")
  
  
  
  output<- list(vars_dataset= data_covars_path, spatial_dataset=spatial_covars_path)
  




#### Outputing result to JSON ####

# Write the output list to the 'output.json' file in JSON format
setwd(outputFolder)
jsonlite::write_json(output, "output.json", auto_unbox = TRUE, pretty = TRUE)