/**
 * BON in a Box - Script service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jean-michel.lord@mcgill.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InfoOutputs model module.
 * @module model/InfoOutputs
 * @version 1.0.0
 */
class InfoOutputs {
    /**
     * Constructs a new <code>InfoOutputs</code>.
     * @alias module:model/InfoOutputs
     */
    constructor() { 
        
        InfoOutputs.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InfoOutputs</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InfoOutputs} obj Optional instance to populate.
     * @return {module:model/InfoOutputs} The populated <code>InfoOutputs</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InfoOutputs();

            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('label')) {
                obj['label'] = ApiClient.convertToType(data['label'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('example')) {
                // JM Lord: Current version of the generator does not work when type is "oneOf" in OpenAPI spec.
                // We want the default convertToType clause to execute.
                obj['example'] = ApiClient.convertToType(data['example'], 'depends on type');
            }
        }
        return obj;
    }


}

/**
 * @member {String} description
 */
InfoOutputs.prototype['description'] = undefined;

/**
 * @member {String} label
 */
InfoOutputs.prototype['label'] = undefined;

/**
 * @member {String} type
 */
InfoOutputs.prototype['type'] = undefined;

/**
 * @member {String} example
 */
InfoOutputs.prototype['example'] = undefined;






export default InfoOutputs;

