/**
 * BON in a Box - Script service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jean-michel.lord@mcgill.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
//import InfoOutputsValueExample from './InfoOutputsValueExample';

/**
 * The InfoOutputsValue model module.
 * @module model/InfoOutputsValue
 * @version 1.0.0
 */
class InfoOutputsValue {
    /**
     * Constructs a new <code>InfoOutputsValue</code>.
     * @alias module:model/InfoOutputsValue
     */
    constructor() { 
        
        InfoOutputsValue.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InfoOutputsValue</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InfoOutputsValue} obj Optional instance to populate.
     * @return {module:model/InfoOutputsValue} The populated <code>InfoOutputsValue</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InfoOutputsValue();

            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('label')) {
                obj['label'] = ApiClient.convertToType(data['label'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('range')) {
                obj['range'] = ApiClient.convertToType(data['range'], ['Number']);
            }
            if (data.hasOwnProperty('options')) {
                obj['options'] = ApiClient.convertToType(data['options'], ['String']);
            }
            if (data.hasOwnProperty('example')) {
                // JM Lord: Current version of the generator does not work when type is "oneOf" in OpenAPI spec.
                // We want the default convertToType clause to execute.
                obj['example'] = ApiClient.convertToType(data['example'], 'depends on type');
            }
        }
        return obj;
    }


}

/**
 * @member {String} description
 */
InfoOutputsValue.prototype['description'] = undefined;

/**
 * @member {String} label
 */
InfoOutputsValue.prototype['label'] = undefined;

/**
 * @member {String} type
 */
InfoOutputsValue.prototype['type'] = undefined;

/**
 * @member {Array.<Number>} range
 */
InfoOutputsValue.prototype['range'] = undefined;

/**
 * @member {Array.<String>} options
 */
InfoOutputsValue.prototype['options'] = undefined;

/**
 * @member {module:model/InfoOutputsValueExample} example
 */
InfoOutputsValue.prototype['example'] = undefined;






export default InfoOutputsValue;

