/**
 * BON in a Box - Script service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jean-michel.lord@mcgill.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InfoReferences model module.
 * @module model/InfoReferences
 * @version 1.0.0
 */
class InfoReferences {
    /**
     * Constructs a new <code>InfoReferences</code>.
     * @alias module:model/InfoReferences
     */
    constructor() { 
        
        InfoReferences.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InfoReferences</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InfoReferences} obj Optional instance to populate.
     * @return {module:model/InfoReferences} The populated <code>InfoReferences</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InfoReferences();

            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
            if (data.hasOwnProperty('doi')) {
                obj['doi'] = ApiClient.convertToType(data['doi'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} text
 */
InfoReferences.prototype['text'] = undefined;

/**
 * @member {String} doi
 */
InfoReferences.prototype['doi'] = undefined;






export default InfoReferences;

