# Load required packages - libraries to run the script ####

## Check and install necessary libraries - packages  ####
packagesPrev<- installed.packages()[,"Package"] # Check and get a list of installed packages in this machine and R version
packagesNeed<- c("magrittr", "dplyr" , "this.path", "rjson", "sf", "rgbif") # Define the list of required packages to run the script
new.packages <- packagesNeed[!(packagesNeed %in% packagesPrev)]; if(length(new.packages)) {install.packages(new.packages, binary=T, force=T, dependencies = F, repos= "https://packagemanager.posit.co/cran/__linux__/jammy/latest")} # Check and install required packages that are not previously installed

## Load the necessary libraries into the script environment ####
packagesList<-list("magrittr", "rgbif") # Explicitly list the required packages throughout the entire routine. Explicitly listing the required packages throughout the routine ensures that only the necessary packages are listed. Unlike 'packagesNeed', this list includes packages with functions that cannot be directly called using the '::' syntax. By using '::', specific functions or objects from a package can be accessed directly without loading the entire package. Loading an entire package involves loading all the functions and objects 
lapply(packagesList, library, character.only = TRUE)  # Load libraries - packages  


# Set enviroment variables ####

### Define output folder path ####
#### Option 1: Setting for production pipeline purposes. ####
##### This is designed for use in a production environment or workflow.
Sys.setenv(outputFolder = "/path/to/output/folder")

#### Option 2: Recommended for debugging purposes to be used as a testing environment. ####
##### This is designed to facilitate script testing and correction
if ( (!exists("outputFolder"))  ) {
  outputFolder<- {x<- this.path::this.path();  file_prev<-  paste0(gsub("/scripts.*", "/output", x), gsub("^.*/scripts", "", x)  ); options<- tools::file_path_sans_ext(file_prev) %>% {c(., paste0(., ".R"), paste0(., "_R"))}; folder_out<- options %>% {.[file.exists(.)]} %>% {.[which.max(sapply(., function(info) file.info(info)$mtime))]}; folder_final<- list.files(folder_out, full.names = T) %>% {.[which.max(sapply(., function(info) file.info(info)$mtime))]} }
}

### Define input folder path ####
#### Set the 'input' environment variables. The 'input' environment contains the specified inputs from the ByB platform.
#### The input file 'input.json' is generated by executing the 'Run Script' command in the ByB platform.
input <- rjson::fromJSON(file=file.path(outputFolder, "input.json")) # Load input file

#### Adjusts the input values paths ####
##### This section adjusts the input values based on specific conditions to rectify and prevent errors in the input paths
input<- lapply(input, function(x) { if (!is.null(x) && length(x) > 0 && grepl("/", x) && !grepl("http://", x)  ) { 
  sub("/output/.*", "/output", outputFolder) %>% dirname() %>%  file.path(x) %>% {gsub("//+", "/", .)}  } else{x} }) 

#  Script body ####

## Set the ISO code of the country of interest ####
if(!is.null(input$country)){
country_table<- rgbif::enumeration_country()
id_country<- tryCatch({dplyr::filter(country_table, title == input$country)[1,1] }, error= function(e){NULL}) %>% {if(is.na(.)){NULL}else{.}}
} else {id_country<- NULL }


## Set the WKT for the study area ####
map_vector<- sf::st_read(input$vector_polygon) %>% 
  sf::st_transform(4326) # 4326 WGS84 coordinates (GBIF standard)

map_wkt<- sf::st_convex_hull(sf::st_union(map_vector)) %>% 
    sf::st_simplify(dTolerance = 0.01) %>% sf::st_as_sf() %>% sf::st_set_geometry("geometry") %>% 
    {sf::st_as_text(.$geometry)}
  
## Load GBIF occurrences - Study area ####
species_key <- rgbif::name_suggest(q = input$species, rank = "species")[[1]]$key[1] ### Get GBIF species id ####
record_count <- rgbif::occ_count(taxonKey = species_key, geometry = map_wkt, country= id_country) ### Estimate  number of available occurrences ####
records <- rgbif::occ_search(taxonKey = species_key, limit = record_count, geometry= map_wkt, country= id_country) ### Download occurrences ####

## Spatialize occurrences ####
records_sf <- records$data %>% sf::st_as_sf(coords = c("decimalLongitude", "decimalLatitude"), crs = 4326)
records_mask<- records_sf[sf::st_within(records_sf, map_vector, sparse = FALSE), ]
convex_mask<- sf::st_convex_hull(sf::st_union(records_mask))
  
  data_mask<- sf::st_drop_geometry(records_mask) %>% as.data.frame()
  
  #  Export results ####
  data_mask_path<- file.path(outputFolder, paste0("data_mask", ".csv")) # Define the file path for the 'val_wkt_path' output
  write.csv(data_mask, data_mask_path, row.names = F) # write result
  
  vector_presence_path<- file.path(outputFolder, "vector_presence_path.GeoJSON") # Define the file path for the 'val_wkt_path' output
  sf::st_write(records_mask, vector_presence_path, delete_dsn= T, driver = "GeoJSON")
  

  # Set Output list ####
  output<- list(data_presence = data_mask_path, vector_presence = vector_presence_path )

  
# Outputing result to JSON ####
setwd(outputFolder)
jsonlite::write_json(output, "output.json", auto_unbox = TRUE, pretty = TRUE)