
# Set session parameters ####

## Load libraries to run the script ####

### Check and Install necessary libraries ####
packagesPrev<- installed.packages()[,"Package"] # Check and get a list of installed packages in this machine and R version
packagesNeed<- c("magrittr", "this.path", "rjson", "data.table", "dplyr", "sf", "fasterize") # Define the list of required packages to run the script
new.packages <- packagesNeed[!(packagesNeed %in% packagesPrev)]; if(length(new.packages)) {install.packages(new.packages, binary=T, force=T, dependencies = F, repos= "https://packagemanager.posit.co/cran/__linux__/jammy/latest")} # Check and install required packages that are not previously installed

### Load libraries ####
packagesList<-list("magrittr", "terra", "raster") # Explicitly list the required packages throughout the entire routine. Explicitly listing the required packages throughout the routine ensures that only the necessary packages are listed. Unlike 'packagesNeed', this list includes packages with functions that cannot be directly called using the '::' syntax. By using '::', specific functions or objects from a package can be accessed directly without loading the entire package. Loading an entire package involves loading all the functions and objects 
lapply(packagesList, library, character.only = TRUE)  # Load libraries - packages  


# Set up the working environment ####

## Set output folder ####
# Option 1: Setting for production pipeline purposes. This is designed for use in a production environment or workflow.
Sys.setenv(outputFolder = "/path/to/output/folder")

# Option 2: Recommended for debugging purposes to be used as a testing environment. This is designed to facilitate script testing and correction
if ( (!exists("outputFolder"))  ) {
  outputFolder<- {x<- this.path::this.path();  file_prev<-  paste0(gsub("/scripts.*", "/output", x), gsub("^.*/scripts", "", x)  ); options<- tools::file_path_sans_ext(file_prev) %>% {c(., paste0(., ".R"), paste0(., "_R"))}; folder_out<- options %>% {.[file.exists(.)]} %>% {.[which.max(sapply(., function(info) file.info(info)$mtime))]}; folder_final<- list.files(folder_out, full.names = T) %>% {.[which.max(sapply(., function(info) file.info(info)$mtime))]} }
}

## Set input folder ####
# Set the 'input' environment variables. The 'input' environment contains the specified inputs from the ByB platform. The input file 'input.json' is generated by executing the 'Run Script' command in the ByB platform.
input <- rjson::fromJSON(file=file.path(outputFolder, "input.json")) # Load input file

# This lines adjusts the input values based on specific conditions to rectify and prevent errors in the input paths
input<- lapply(input, function(y) lapply(y, function(x)  { if (!is.null(x) && length(x) > 0 && grepl("/", x) && !grepl("http://", x)  ) { 
  sub("/output/.*", "/output", outputFolder) %>% dirname() %>%  file.path(x) %>% {gsub("//+", "/", .)}  } else{x} }) %>% unlist()) 


#  Script body ####

output<- (function(){
  
  ## Load data ####
  
  #### Load crs projection ####
  crs_basemap<- raster::crs( paste0("+init=epsg:", input$EPSG_grid) )
  
  #### Load vector StudyArea ####
  vector_polygon<-  terra::vect(input$StudyArea_vector) %>% terra::aggregate()  %>%  terra::project( crs_basemap    ) %>% sf::st_as_sf()

  #### Adjust grid projection ####
  # Adjusted projection to the planar coordinate system  EPSG 3395.
  ext_polygon<- sf::st_bbox(vector_polygon)
  ext_polygon_3395 <- sf::st_bbox(vector_polygon) %>% sf::st_as_sfc() %>% sf::st_transform(3395) %>% sf::st_as_sf() %>%  raster::extent()
  raster_base_3395<- raster::raster(ext_polygon_3395,crs = 3395, res= input$Resolution_grid )
  
  ## Create grid base ####
  raster_base<- raster_base_3395 %>% raster::projectRaster(crs= crs_basemap)

  ## Create Study Area base ####
  raster_study_area<- fasterize::fasterize(vector_polygon, raster_base) %>% terra::rast()
  levels(raster_study_area)<- data.frame(values= 1, label= "Study area")
  coltab(raster_study_area)<- data.frame(values= 1, cols= "gray")
  
  
  ## Write results ####  
  StudyArea_grid_path<- file.path(outputFolder, paste0("StudyArea_grid", ".tif")) # Define the file path 
  terra::writeRaster(raster_study_area, StudyArea_grid_path, gdal=c("COMPRESS=DEFLATE", "TFW=YES"), filetype = "GTiff", overwrite = TRUE ) # write result
  
  StudyArea_vector_path<- file.path(outputFolder, paste0("StudyArea_vector", "GeoJSON")) # Define the file path 
  sf::st_write(vector_polygon, StudyArea_vector_path, delete_dsn= T, driver = "GeoJSON")
  
  # Define final output list
  output<- list(StudyArea_grid= StudyArea_grid_path, StudyArea_vector= StudyArea_vector_path)

})()




#### Outputing result to JSON ####

# Write the output list to the 'output.json' file in JSON format
setwd(outputFolder)
jsonlite::write_json(output, "output.json", auto_unbox = TRUE, pretty = TRUE)