
#### Load required packages - libraries to run the script ####

# Install necessary libraries - packages  
packagesPrev<- installed.packages()[,"Package"] # Check and get a list of installed packages in this machine and R version
# Install necessary libraries - packages  
packagesPrev<- installed.packages()[,"Package"] # Check and get a list of installed packages in this machine and R version
packagesNeed<- c("magrittr", "data.table", "reshape2", "dplyr", "plyr", "ggplot2", "tibble", "pbapply", "rredlist", "plyr", "red", "gdistance", "BAT", "ape", "geometry", "magic", "hypervolume", "ks", "mclust", "mvtnorm","pracma","fastcluster", "pdist","palmerpenguins","caret","recipes", "timeDate", "gower", "hardhat","ipred", "prodlim", "lava","future.apply", "future", "globals", "listenv", "parallelly", "ModelMetrics","pROC", "nls2", "proto", "vegan","permute","phytools", "combinat", "clusterGeneration", "DEoptim", "expm", "optimParallel", "phangorn", "fastmatch", "scatterplot3d", "predicts","coda", "mnormt", "numDeriv", "quadprog") # Define the list of required packages to run the script
new.packages <- packagesNeed[!(packagesNeed %in% packagesPrev)]; if(length(new.packages)) {install.packages(new.packages, binary=T, force=T, dependencies = F, repos= "https://packagemanager.posit.co/cran/__linux__/jammy/latest")} # Check and install required packages that are not previously installed

# Load libraries
packagesList<-list("magrittr", "ggplot2") # Explicitly list the required packages throughout the entire routine. Explicitly listing the required packages throughout the routine ensures that only the necessary packages are listed. Unlike 'packagesNeed', this list includes packages with functions that cannot be directly called using the '::' syntax. By using '::', specific functions or objects from a package can be accessed directly without loading the entire package. Loading an entire package involves loading all the functions and objects 
lapply(packagesList, library, character.only = TRUE)  # Load libraries - packages  

Sys.setenv(outputFolder = "/path/to/output/folder")

# Option 2: Recommended for debugging purposes to be used as a testing environment. This is designed to facilitate script testing and correction
if ( (!exists("outputFolder"))  ) {
  outputFolder<- {x<- this.path::this.path();  file_prev<-  paste0(gsub("/scripts.*", "/output", x), gsub("^.*/scripts", "", x)  ); options<- tools::file_path_sans_ext(file_prev) %>% {c(., paste0(., ".R"), paste0(., "_R"))}; folder_out<- options %>% {.[file.exists(.)]} %>% {.[which.max(sapply(., function(info) file.info(info)$mtime))]}; folder_final<- list.files(folder_out, full.names = T) %>% {.[which.max(sapply(., function(info) file.info(info)$mtime))]} }
}

# Set the 'input' environment variables. The 'input' environment contains the specified inputs from the ByB platform.
# The input file 'input.json' is generated by executing the 'Run Script' command in the ByB platform.
input <- rjson::fromJSON(file=file.path(outputFolder, "input.json")) # Load input file

# This section adjusts the input values based on specific conditions to rectify and prevent errors in the input paths
input<- lapply(input, function(x) { if (!is.null(x) && length(x) > 0 && grepl("/", x) && !grepl("http://", x)  ) { 
  sub("/output/.*", "/output", outputFolder) %>% dirname() %>%  file.path(x) %>% {gsub("//+", "/", .)}  } else{x} }) 



#### Species list by country ####
#Load IUCN token----
historyassesment_data<-  data.table::fread(input$historyassesment_data) %>% as.data.frame()
form_matrix<- as.formula(paste0(input$sp_col, "~", input$time_col))


historyAssesment_matrix<-   reshape2::dcast(historyassesment_data, form_matrix,  value.var = "code",
                                                 fun.aggregate = function(x) {unique(x)[1]}
) %>% tibble::column_to_rownames(input$sp_col) %>% as.data.frame.matrix()



# Ajustar matriz de codigos de amenaza ####

########## Codigo redlist
adjust_categories<- data.frame(Cat_IUCN= c("CR", "DD", "EN", "EN", "DD", "DD", "LC", "LC", "LC", "NT", "DD", "NT", "RE", "VU", "VU"),
                               code= c("CR", "DD", "E", "EN", "I", "K", "LC", "LR/cd", "LR/lc", "LR/nt", "NA", "NT", "R", "V", "VU"))

redList_matrix<- historyAssesment_matrix %>% as.matrix()

for(i in seq(nrow(adjust_categories))){
  redList_matrix[ which(redList_matrix== adjust_categories[i,]$code, arr.ind = TRUE) ]<- adjust_categories[i,]$Cat_IUCN 
}

for(j in unique(adjust_categories$Cat_IUCN)){
  key<- c(tolower(j), toupper(j), j) %>% paste0(collapse = "|")
  redList_matrix[ which(grepl(key, redList_matrix), arr.ind = T) ]    <- j
}

redList_matrix[which( (!redList_matrix %in% adjust_categories$Cat_IUCN)  & !is.na(redList_matrix) , arr.ind = TRUE )]<-NA


# Redlist data ####
print("red")
redlist_data<- red::rli(redList_matrix, boot = F) %>% t() %>% as.data.frame() %>% tibble::rownames_to_column("Year") %>%  setNames(c("Year", "RLI")) %>% 
  dplyr::filter(!Year %in% "Change/year")
print("redlist_data")


# Redlist figura ####
redlist_trendplot<- ggplot(redlist_data, aes(x = Year, y = RLI)) +
  geom_line(group = 1, col= "red") +
  geom_point() +
  coord_cartesian(ylim = c(0,1))+
  theme_classic()+
  theme(    panel.grid.major = element_line(color = "gray"),
) + theme(text = element_text(size = 4))



## Write results ####  
redlist_data_path<- file.path(outputFolder, paste0("redlist_data", ".csv")) # Define the file path 
write.csv(redlist_data, redlist_data_path, row.names = F) # write result

redList_matrix_path<- file.path(outputFolder, paste0("redList_matrix", ".csv")) # Define the file path 
write.csv(redList_matrix, redList_matrix_path, row.names = T) # write result

redlist_trendplot_path<- file.path(outputFolder, paste0("redlist_trendplot", ".jpg")) # Define the file path 
ggsave(redlist_trendplot_path, redlist_trendplot, height = 2, width = 4)


#### Outputing result to JSON ####

output<- list(redlist_trendplot= redlist_trendplot_path, redlist_data= redlist_data_path, redList_matrix= redList_matrix_path )

# Write the output list to the 'output.json' file in JSON format
setwd(outputFolder)
jsonlite::write_json(output, "output.json", auto_unbox = TRUE, pretty = TRUE)





