name: R Runner, main branch

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'runners/r-dockerfile'

jobs:
  runner-r:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: geobon/bon-in-a-box
        tags: |
          # Image used in compose file
          type=raw,value=runner-r
          # In case we want to replicate a specific legacy setup
          type=sha,prefix=runner-r-
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: runners
        file: runners/r-dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
  
